Repository google/exposure-notifications-server, pull requests merged in 2020-09, with the labels that each got.

#936 Update Deps
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XL

#938 Add myself to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#942 Fix copy-pasta
  builders/deploy.yaml
  builders/promote.yaml
Labels: approved, cla: yes, lgtm, size/S

#943 Fix dropping all labels
  pkg/observability/resource.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/M

#944 Revert "Update Deps (#936)"
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XL

#945 Update dependencies, locking sys at f9321e4
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XL

#946 specify required JWT headers on verification certificates
  docs/design/verification_protocol.md
Labels: approved, cla: yes, lgtm, size/XS

#947 Don't use the zap logger for migrations
  cmd/migrate/main.go
Labels: approved, cla: yes, lgtm, size/M

#950 Update terraform to 1.13.1 in docker and install jq
  docker/presubmit-test.dockerfile
Labels: approved, cla: yes, lgtm, size/S

#951 Fix some stackdriver bugs
  pkg/observability/resource.go
  pkg/observability/stackdriver.go
  pkg/server/server.go
Labels: approved, cla: yes, lgtm, size/M

#952 add base64 decode tool for inspecting hmac candidates
  tools/b64decode/main.go
Labels: approved, cla: yes, lgtm, size/M

#954 fix docs misspelling of verification claim field
  docs/design/verification_protocol.md
Labels: approved, cla: yes, lgtm, size/XS

#957 Switch InMemory KMS to filesystem based
  internal/integration/helpers.go
  internal/keyrotation/rotate_test.go
  internal/keyrotation/server_test.go
  internal/publish/publish_test.go
  internal/revision/database/revision_test.go
  internal/revision/revision_test.go
  internal/setup/setup_test.go
  pkg/keys/config.go
  pkg/keys/filesystem.go
  pkg/keys/filesystem_test.go
  pkg/keys/google_cloud_kms.go
  pkg/keys/hashicorp_vault.go
  pkg/keys/in_memory.go
  pkg/keys/keys.go
  pkg/keys/testing.go
Labels: approved, cla: yes, lgtm, size/XXL

#958 Update healthauthority.html
  tools/admin-console/templates/healthauthority.html
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#959 implement random padding of publish responses
  internal/publish/config.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
Labels: approved, cla: yes, lgtm, size/M

#948 Smoke test terraform deployment
  scripts/e2e-test.sh
  scripts/e2e_test.sh
  scripts/terraform.sh
  terraform-e2e/README.md
  terraform-e2e/main.tf
  terraform-e2e/state.tf
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/L

#960 Fix promote step names
  builders/promote.yaml
Labels: approved, cla: yes, lgtm, size/S

#962 Update deps
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/M

#961 add ability to print signature info in export-analyzer
  internal/export/exportfile.go
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/M

#967 Add x-api-version header in API responses
  internal/publish/publish.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
Labels: approved, cla: yes, lgtm, size/XS

#970 Upgrade to Go 1.15.1
  CONTRIBUTING.md
  Dockerfile
  builders/build.yaml
  docker/migrate.dockerfile
  docker/presubmit-test.dockerfile
  docker/protoc.dockerfile
Labels: approved, cla: yes, lgtm, size/M

#969 Fix double-quoted padding
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/XS

#968 Ensure /v1/publish/ returns a 404
  cmd/exposure/main.go
Labels: approved, cla: yes, lgtm, size/XS

#971 Rename bucket_policy_only -> uniform_bucket_level_access
  terraform/build.tf
  terraform/storage.tf
Labels: approved, cla: yes, lgtm, size/S

#963 Use revision tokens in generate service
  internal/generate/generate_test.go
  internal/generate/handler.go
Labels: approved, cla: yes, lgtm, size/L

#972 Add comment
  internal/generate/handler.go
Labels: approved, cla: yes, lgtm, size/XS

#973 add migrations for exporter-importer
  migrations/000038_add_imports.down.sql
  migrations/000038_add_imports.up.sql
Labels: approved, cla: yes, lgtm, size/M

#975 Fix AAD acronym, clarify long form
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/XS

#964 Add support for partial revisions
  internal/export/database/export_test.go
  internal/federationin/federationin.go
  internal/federationin/federationin_test.go
  internal/generate/handler.go
  internal/performance/export_test.go
  internal/publish/config.go
  internal/publish/database/exposure.go
  internal/publish/database/exposure_test.go
  internal/publish/model/exposure_model.go
  internal/publish/publish.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
Labels: approved, cla: yes, lgtm, size/XL

#978 Install boskosctl, the GCP projects pool manager in presubmit test image
  docker/presubmit-test.dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#979 Return more specific error codes for key_already_revised and invalid_report_type_transition
  internal/authorizedapp/database_provider.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  pkg/api/v1/exposure_types.go
Labels: approved, cla: yes, lgtm, size/L

#976 Run terraform smoke test with dynamic projects
  .gitignore
  scripts/e2e-test.sh
  scripts/terraform.sh
  terraform-e2e/state.tf
Labels: approved, cla: yes, lgtm, size/M

#982 fix docs about observability exporter values; fix other minor doc bugs
  RELEASING.md
  docs/getting-started/deploying.md
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#980 Support signing interface in Azure KeyVault
  pkg/keys/azure_keyvault.go
Labels: approved, cla: yes, lgtm, size/L

#983 Sort exposures in unit test to make the result deterministic
  internal/publish/database/exposure_test.go
Labels: approved, cla: yes, lgtm, size/XS

#953 Adds the option to perform Bulk exposure updates
  internal/performance/export_test.go
  internal/publish/database/exposure.go
  internal/publish/database/performance_test_utils.go
  internal/publish/database/performance_test_utils_test.go
Labels: approved, cla: yes, lgtm, size/L

#984 Expand log based metrics with opencensus metrics
  internal/cleanup/cleanup.go
  internal/export/batcher.go
  internal/export/worker.go
  internal/federationin/federationin.go
  internal/federationout/federationout.go
  internal/keyrotation/rotate.go
  internal/metrics/cleanup/measurements.go
  internal/metrics/cleanup/views.go
  internal/metrics/export/measurements.go
  internal/metrics/export/views.go
  internal/metrics/federationin/measurements.go
  internal/metrics/federationin/views.go
  internal/metrics/federationout/measurements.go
  internal/metrics/federationout/views.go
  internal/metrics/meta.go
  internal/metrics/metricsware/cleanup.go
  internal/metrics/metricsware/export.go
  internal/metrics/metricsware/federationin.go
  internal/metrics/metricsware/federationout.go
  internal/metrics/metricsware/middleware.go
  internal/metrics/metricsware/publish.go
  internal/metrics/metricsware/rotate.go
  internal/metrics/publish/measurements.go
  internal/metrics/publish/views.go
  internal/metrics/rotate/measurements.go
  internal/metrics/rotate/views.go
  internal/publish/publish.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/XL

#985 add migration to revert export import
  migrations/000039_UndoImportExport.down.sql
  migrations/000039_UndoImportExport.up.sql
Labels: approved, cla: yes, lgtm, size/M

#989 add tool to sign a string with all signing keys in a DB
  tools/sign/main.go
Labels: approved, cla: yes, lgtm, size/L

#992 Move skip GCS tests into a helper
  internal/storage/google_cloud_storage_test.go
Labels: approved, cla: yes, lgtm, size/S

#993 add tool to verify ASN1 encoded signatures of digests with a provided…
  tools/sign/main.go
  tools/verify/main.go
Labels: approved, cla: yes, lgtm, size/L

#994 Minor update to release process
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/XS

#990 Making stackdriver exporter options configurable in env var
  pkg/observability/config.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/S

#996 Make migrate executable
  builders/build.yaml
  builders/cloud-sql-exec
  builders/migrate.dockerfile
  docker/migrate.dockerfile
  docker/urlencode
Labels: approved, cla: yes, lgtm, size/M

#997 Fix terraform trap destroy
  scripts/terraform.sh
Labels: approved, cla: yes, lgtm, size/XS

#1000 set text/plain content type when uploading index.txt files
  internal/export/worker.go
  internal/storage/aws_s3.go
  internal/storage/azure_blobstore.go
  internal/storage/filesystem_storage.go
  internal/storage/filesystem_storage_test.go
  internal/storage/google_cloud_storage.go
  internal/storage/google_cloud_storage_test.go
  internal/storage/memory.go
  internal/storage/noop.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, size/M

#1002 Explicitly set application/zip on zip files.
  internal/export/worker.go
  internal/storage/filesystem_storage_test.go
  internal/storage/google_cloud_storage_test.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, size/XS

#999 Add a timeout knob to control stackdriver exporter behavior.
  pkg/observability/config.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/XS

#1005 restore previous handling of too large symptom onset
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
Labels: approved, cla: yes, lgtm, size/S

#1006 add padding recommendations to docs
  pkg/api/v1/exposure_types.go
  pkg/api/v1alpha1/exposure_types.go
Labels: approved, cla: yes, lgtm, size/XS

#1008 Fix exit status for export-analyzer tool
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1009 Fix e2e test failure when there is no authorized app
  internal/e2e/e2e_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1012 Set Content-Type response header as application/json on publish responses
  internal/publish/publish_test.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
Labels: approved, cla: yes, lgtm, size/S

#1013 Return warnings instead of error when symptom onset is too long ago
  docs/getting-started/publishing-temporary-exposure-keys.md
  internal/generate/handler.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  internal/publish/publish_v1alpha1.go
  pkg/api/v1/exposure_types.go
  pkg/api/v1alpha1/exposure_types.go
Labels: approved, cla: yes, lgtm, size/L

#998 Add key synchronization with a JWKS endpoint.
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
  cmd/jwks-updater/main.go
  docs/getting-started/deploying.md
  go.mod
  go.sum
  internal/admin/healthauthority/form.go
  internal/admin/healthauthority/keys.go
  internal/serverenv/env.go
  internal/setup/setup.go
  internal/verification/database/health_authority_db.go
  internal/verification/model/health_authority.go
  migrations/000040_AddJwksUri.down.sql
  migrations/000040_AddJwksUri.up.sql
  pkg/jwks/jwks.go
  pkg/jwks/jwks_test.go
  terraform/service_jwks.tf
  tools/admin-console/templates/healthauthority.html
Labels: approved, cla: yes, lgtm, size/XXL

#1014 Fix Terraform configs
  terraform/service_jwks.tf
Labels: approved, cla: yes, lgtm, size/XS

#1015 Add server listener for jwks, fix context propagation
  cmd/jwks-updater/main.go
  internal/serverenv/env.go
  internal/setup/setup.go
  pkg/jwks/jwks.go
  pkg/jwks/jwks_test.go
  pkg/jwks/server.go
Labels: approved, cla: yes, lgtm, size/L

#1016 Ensure jwk can resolve secrets
  cmd/jwks-updater/main.go
  pkg/jwks/jwks.go
Labels: approved, cla: yes, lgtm, size/S

#1017 Check errors from HA database calls
  pkg/jwks/jwks.go
Labels: approved, cla: yes, lgtm, size/XS

#1018 Actually set the manager on the struct
  pkg/jwks/server.go
Labels: approved, cla: yes, lgtm, size/S

#1019 update instructions for export signing and key ordering
  internal/admin/exports/form.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/pb/export/export.pb.go
  internal/pb/export/export.proto
  tools/admin-console/templates/export.html
Labels: approved, cla: yes, lgtm, size/M

#1020 handle nil jwks URI in database
  internal/admin/healthauthority/form.go
  internal/verification/database/health_authority_db_test.go
  internal/verification/model/health_authority.go
  pkg/jwks/jwks.go
  pkg/jwks/jwks_test.go
Labels: approved, cla: yes, lgtm, size/S

#1021 Add stack driver debug logging
  pkg/observability/config.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/M

#1024 Replace github.com/jackc/puddle with a fork.
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#1026 Log HealthAuthority when publishing.
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/XS

#1029 Update Go and deps
  CONTRIBUTING.md
  Dockerfile
  builders/build.yaml
  docker/presubmit-test.dockerfile
  docker/protoc.dockerfile
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/L

#1025 E2E test: hook up with verification
  internal/e2e/e2e_test.go
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/performance/export_test.go
  internal/utils/utils.go
  terraform-e2e/main.tf
Labels: approved, cla: yes, lgtm, size/L

#1031 [Automated] Fix misspellings
  RELEASING.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1032 Make admin console pretty
  docs/images/admin_console_add_authorized_application.png
  docs/images/admin_console_create_new_export_config.png
  docs/images/admin_console_create_new_health_authority.png
  docs/images/admin_console_create_new_signature_info.png
  docs/images/admin_console_landing.png
  internal/admin/authorizedapps/view.go
  internal/admin/exports/view.go
  internal/admin/healthauthority/view.go
  internal/admin/index/index.go
  internal/admin/siginfo/view.go
  internal/admin/util.go
  tools/admin-console/main.go
  tools/admin-console/templates/authorizedapp.html
  tools/admin-console/templates/bottom.html
  tools/admin-console/templates/export.html
  tools/admin-console/templates/healthauthority.html
  tools/admin-console/templates/index.html
  tools/admin-console/templates/siginfo.html
  tools/admin-console/templates/top.html
Labels: approved, cla: yes, lgtm, size/XXL

#1035 Fix perf test
  internal/integration/helpers.go
  internal/performance/export_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1038 Automatic code review: comment wheen there is a new .Errorw added
  .github/workflows/codereview.yaml
Labels: approved, cla: yes, lgtm, size/M

#1039 Fix the metric missing issue caused by repeated metric point upload.
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/XS

#1040 Update release-notes params
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/XS

#1037 Fix incremental e2e test by use new health authority
  internal/e2e/e2e_test.go
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/performance/export_test.go
  internal/utils/utils.go
Labels: approved, cla: yes, lgtm, size/M

#1030 Add local dev docs, make it possible to run both servers locally
  .dockerignore
  docs/getting-started/development.md
  go.mod
  go.sum
  scripts/dev
  testdata/clear-export.sql
  testdata/config.sql
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/XL

#1041 add tek validation guide
  docs/index.md
  docs/tek_validation.md
Labels: approved, cla: yes, lgtm, size/M

#986 Upgrade federation for 1.5+
  cmd/federationout/main.go
  internal/federationin/config.go
  internal/federationin/database/federationin.go
  internal/federationin/database/federationin_test.go
  internal/federationin/federationin.go
  internal/federationin/federationin_test.go
  internal/federationin/model/federation_model.go
  internal/federationout/config.go
  internal/federationout/federationout.go
  internal/federationout/federationout_test.go
  internal/metrics/federationin/measurements.go
  internal/metrics/federationin/views.go
  internal/metrics/metricsware/federationin.go
  internal/pb/federation.pb.go
  internal/pb/federation.proto
  internal/pb/federation/federation.pb.go
  internal/pb/federation/federation.proto
  internal/publish/database/exposure.go
  internal/publish/database/exposure_test.go
  internal/publish/model/exposure_model.go
  migrations/000041_AddTravelerFederation.down.sql
  migrations/000041_AddTravelerFederation.up.sql
  scripts/dev
  tools/federationout-test/main.go
Labels: approved, cla: yes, lgtm, size/XXL

#1042 Also migrate db in incremental e2e test
  scripts/e2e-test.sh
Labels: approved, cla: yes, lgtm, size/XS

#1043 Add security scanning
  .github/workflows/codeql-analysis.yml
Labels: approved, cla: yes, lgtm, size/M

#1022 Revert "Add stack driver debug logging (#1021)"
  pkg/observability/config.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/M

#1027 Move key server specific view registration to a separate function.
  internal/setup/setup.go
  pkg/observability/common/register.go
  pkg/observability/en/register.go
  pkg/observability/noop.go
  pkg/observability/observability.go
  pkg/observability/opencensus.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/L
