Repository google/exposure-notifications-server, pull requests merged in 2020-10, with the labels that each got.

#1045 Terraform: services deployments depdend on DB migration
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/service_jwks.tf
  terraform/service_keyrotation.tf
Labels: approved, cla: yes, lgtm, size/S

#1044 Allow for importing of export files from other servers.
  cmd/export-importer/main.go
  internal/export/exportfile.go
  internal/export/exportfile_test.go
  internal/exportimport/config.go
  internal/exportimport/database/exportimport.go
  internal/exportimport/database/exportimport_test.go
  internal/exportimport/import.go
  internal/exportimport/importer.go
  internal/exportimport/model/exportimport.go
  internal/exportimport/model/file.go
  internal/exportimport/model/importkeys.go
  internal/exportimport/scheduler.go
  internal/exportimport/server.go
  internal/integration/integration_test.go
  internal/performance/export_test.go
  internal/publish/database/exposure.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  migrations/000042_ReAddExportImporterTables.down.sql
  migrations/000042_ReAddExportImporterTables.up.sql
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/XXL

#1050 migration instructions
  docs/server_migration.md
Labels: approved, cla: yes, lgtm, size/M

#1049 E2e test: export test
  internal/e2e/e2e_test.go
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/performance/export_test.go
  scripts/e2e-test.sh
  terraform-e2e/main.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_export.tf
  terraform/storage.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#1052 add migration to nav and readme
  README.md
  docs/_data/navigation.yml
Labels: approved, cla: yes, lgtm, size/XS

#1051 Refactoring how OpenCensus views are registered.
  internal/metrics/cleanup/views.go
  internal/metrics/export/views.go
  internal/metrics/federationin/views.go
  internal/metrics/federationout/views.go
  internal/metrics/publish/views.go
  internal/metrics/rotate/views.go
  internal/setup/setup.go
  pkg/observability/common/register.go
  pkg/observability/en/register.go
  pkg/observability/noop.go
  pkg/observability/observability.go
  pkg/observability/opencensus.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/L

#1053 add infrastructure for export-importer
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
  terraform/service_export_importer.tf
Labels: approved, cla: yes, lgtm, size/L

#1056 Unify custom domain logic
  terraform-e2e/main.tf
  terraform/README.md
  terraform/lb.tf
  terraform/service_debugger.tf
  terraform/service_exposure.tf
  terraform/service_federationout.tf
  terraform/storage.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#1057 Lock merged PRs and closed issues after a day
  .github/workflows/lock.yml
Labels: approved, cla: yes, lgtm, size/S

#1058 Add export-importer image in cloudbuild config
  builders/build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1059 Ensure importer-exporter resolves secrets
  internal/exportimport/config.go
Labels: approved, cla: yes, lgtm, size/XS

#1060 allow for default days since symptom onset
  internal/generate/config.go
  internal/publish/config.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
Labels: approved, cla: yes, lgtm, size/L

#1061 Fix e2e terraform deployment by supplying hosts
  terraform-e2e/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1062 Don't fail terraform if there is no custom domain supplied
  terraform-e2e/main.tf
  terraform/lb.tf
Labels: approved, cla: yes, lgtm, size/XS

#1063 Add chaodaig as approver
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1064 E2E test: fetch exposure url string from collection
  scripts/e2e-test.sh
Labels: approved, cla: yes, lgtm, size/XS

#1065 E2E test: fix flakes by increasing db connection idle waiting time
  internal/e2e/e2e_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1066 E2E test: deflake by waiting longer for export
  internal/e2e/e2e_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1067 Exclude regions in export.
  internal/admin/exports/form.go
  internal/admin/exports/form_test.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/model/export_model.go
  internal/export/worker.go
  migrations/000043_ReAddExcludeRegions.down.sql
  migrations/000043_ReAddExcludeRegions.up.sql
  tools/admin-console/templates/export.html
Labels: approved, cla: yes, lgtm, size/L

#1070 add mirror service
  cmd/mirror/main.go
  internal/mirror/config.go
  internal/mirror/database/mirror.go
  internal/mirror/database/mirror_test.go
  internal/mirror/mirror.go
  internal/mirror/model/mirror.go
  internal/mirror/server.go
  migrations/000044_AddMirrorSettings.down.sql
  migrations/000044_AddMirrorSettings.up.sql
Labels: approved, cla: yes, lgtm, size/XL

#1071 E2E test: add cleanup scenario
  internal/e2e/e2e_test.go
Labels: approved, cla: yes, lgtm, size/M

#1075 Update Errorf usage
  internal/exportimport/importer.go
Labels: approved, cla: yes, lgtm, size/XS

#1076 export-import improvements
  internal/exportimport/database/exportimport.go
  internal/exportimport/database/exportimport_test.go
  internal/exportimport/import.go
  internal/exportimport/importer.go
  internal/exportimport/scheduler.go
  migrations/000045_AddExportImportIndex.down.sql
  migrations/000045_AddExportImportIndex.up.sql
Labels: approved, cla: yes, lgtm, size/L

#1078 Make sure map is initialized
  internal/export/database/export.go
Labels: approved, cla: yes, lgtm, size/XS

#1079 Guray is working on PPA now
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1081 Build and deploy mirror service
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
Labels: approved, cla: yes, lgtm, size/M

#1082 Fix typo in mirror builder
  builders/build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1080 add some export-importer tests
  internal/exportimport/scheduler.go
  internal/exportimport/scheduler_test.go
Labels: approved, cla: yes, lgtm, size/L

#1083 Increase build timeout, use 32 cores
  builders/build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1072 Add OnlyNonTravelers to exports.
  internal/admin/exports/form.go
  internal/export/batcher.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/model/export_model.go
  internal/export/worker.go
  internal/pb/federation/federation.pb.go
  internal/publish/database/exposure.go
  migrations/000046_AddOnlyNonTravelers.down.sql
  migrations/000046_AddOnlyNonTravelers.up.sql
  tools/admin-console/templates/export.html
Labels: approved, cla: yes, lgtm, size/L

#1084 add mirror to migration docs
  docs/server_migration.md
Labels: approved, cla: yes, lgtm, size/XS

#1085 Add export importers to the admin console
  internal/admin/config.go
  internal/admin/controller.go
  internal/admin/exportimporters/form.go
  internal/admin/exportimporters/save.go
  internal/admin/exportimporters/view.go
  internal/admin/exportimporters/view_test.go
  internal/admin/index/index.go
  internal/admin/template.go
  internal/export/model/export_model.go
  internal/export/model/export_model_test.go
  internal/exportimport/database/exportimport.go
  internal/verification/model/health_authority.go
  tools/admin-console/main.go
  tools/admin-console/templates/export-importer.html
  tools/admin-console/templates/export.html
  tools/admin-console/templates/healthauthority.html
  tools/admin-console/templates/index.html
Labels: approved, cla: yes, lgtm, size/XL

#1088 Add timeutils from exposure notification verification server
  pkg/timeutil/midnight.go
Labels: approved, cla: yes, lgtm, size/M

#1090 Add jeremyfaller to reviewers and maintainers.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1091 Fix name on timeutils package.
  pkg/timeutils/midnight.go
Labels: approved, cla: yes, lgtm, size/XS

#1093 Require TLS 1.2+
  terraform/lb.tf
Labels: approved, cla: yes, lgtm, size/XS

#1094 Incremental e2e test uses terraform instead of scripts
  scripts/e2e-test.sh
Labels: approved, cla: yes, lgtm, size/S

#1095 Efgs upload model
  internal/efgs/regions.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/model/export_model.go
  migrations/000047_AddEFGSUploadConfig.down.sql
  migrations/000047_AddEFGSUploadConfig.up.sql
Labels: approved, cla: yes, lgtm, size/L

#1096 Fix e2e test: one more E2E_GOOGLE_CLOUD_BUCKET
  internal/integration/helpers.go
Labels: approved, cla: yes, lgtm, size/XS

#1097 Terraform db instance explicitly depends_on db, cert and user
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/XS

#1092 Fix uses of time.Truncate
  internal/publish/model/exposure_model_test.go
  pkg/util/generate.go
  tools/interval/main.go
Labels: approved, cla: yes, lgtm, size/S

#1099 e2e test script is guarded against prod resources
  scripts/terraform.sh
Labels: approved, cla: yes, lgtm, size/S

#1100 Document setting versioning and lifecycle on Terraform state
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/S

#1101 E2E test: update usage of gcloud to prevent breakage from future brea…
  scripts/terraform.sh
Labels: approved, cla: yes, lgtm, size/S

#1104 Add headlesss-shell in presubmit test image
  docker/presubmit-test.dockerfile
Labels: approved, cla: yes, lgtm, size/S

#1106 Export analyzer nil error
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/S

#1103 take user provided symptom onset in publish
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
Labels: approved, cla: yes, lgtm, size/M

#1107 Minor spelling nits
  internal/admin/exports/save.go
  internal/admin/exports/view.go
  internal/admin/index/index.go
  internal/debugger/handler_debug.go
  internal/export/database/export.go
  internal/exportimport/database/exportimport_test.go
  internal/jsonutil/unmarshal.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
  tools/federationout-test/main.go
  tools/sign/main.go
Labels: approved, cla: yes, lgtm, size/S

#1109 factor out generate regions, add traveler generate
  internal/generate/config.go
  internal/generate/handler.go
Labels: approved, cla: yes, lgtm, size/S

#1110 Rename all e2e test scripts to make people not want to run them locally
  .gitignore
  scripts/ci-e2e-test.sh
  scripts/ci-terraform.sh
  terraform-e2e-ci/README.md
  terraform-e2e-ci/main.tf
Labels: approved, cla: yes, lgtm, size/S

#1112 still mint revision token if one was provided before, but no new data
  internal/publish/publish_test.go
  internal/revision/revision.go
  internal/revision/revision_test.go
Labels: approved, cla: yes, lgtm, size/L

#1098 Terraform e2e: add back custom db deletion step
  scripts/ci-terraform.sh
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/S

#1114 Fixed a spelling mistake
  docs/index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1115 Fix typos in comments and docs
  docs/design/verification_protocol.md
  docs/getting-started/downloading-export-batches-keys.md
  docs/getting-started/publishing-temporary-exposure-keys.md
  internal/verification/phaverify.go
  internal/verification/phaverify_test.go
  pkg/api/v1/exposure_types.go
  pkg/api/v1alpha1/exposure_types.go
  pkg/api/v1alpha1/verification_types.go
  pkg/keys/hashicorp_vault.go
  pkg/keys/keys.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1116 Nit: share the db instances
  internal/export/batcher.go
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/S

#1117 Terrafrom smoke test: don't fail if failed to taint build/migrate
  scripts/ci-e2e-test.sh
Labels: approved, cla: yes, lgtm, size/S

#1123 Handle nil multierror
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1118 Try using full Chrome for now
  docker/presubmit-test.dockerfile
  pkg/server/server.go
Labels: approved, cla: yes, lgtm, size/M

#1124 fix nit with multierror
  internal/keyrotation/rotate.go
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/S

#1120 update release cadence
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/XS

#1125 Update observability exporter to use a new ctx.
  internal/setup/setup.go
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/XS

#1122 certificate verification improvements
  internal/publish/config.go
  internal/publish/publish.go
  internal/verification/database/health_authority_db.go
  internal/verification/database/health_authority_db_test.go
  internal/verification/phaverify.go
  internal/verification/phaverify_test.go
Labels: approved, cla: yes, lgtm, size/L

#1119 write generated export padding to the database, ensure overlapping ex…
  internal/database/lock.go
  internal/database/lock_test.go
  internal/export/config.go
  internal/export/database/export.go
  internal/export/worker.go
  internal/export/worker_test.go
  internal/pb/federation/federation.pb.go
  internal/publish/database/exposure.go
Labels: approved, cla: yes, lgtm, size/XL

#1130 Get the keys from the DB while handling a HA JWKS update.
  pkg/jwks/jwks.go
  pkg/jwks/jwks_test.go
Labels: approved, cla: yes, lgtm, size/S
