Repository google/exposure-notifications-server, pull requests merged in 2020-05, with the labels that each got.

#255 fix links in README
  README.md
  docs/index.md
Labels: approved, cla: yes, lgtm, size/XS

#258 remove apk signing key sha256 requirement
  internal/pb/export/export.pb.go
  internal/pb/export/export.proto
Labels: approved, cla: yes, lgtm, size/XS

#259 Add mono entrypoint that runs all the handlers
  CONTRIBUTING.md
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/export/main.go
  cmd/monolith/main.go
  go.sum
  internal/api/cleanup/cleanup.go
Labels: approved, cla: yes, lgtm, size/L

#261 specify valid characters for verification key id
  internal/pb/export/export.pb.go
  internal/pb/export/export.proto
Labels: approved, cla: yes, lgtm, size/XS

#264 Fix newline
  docs/index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#265 Fix 404 on Reference Documentation link
  README.md
  docs/index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#266 allow for gaps, ensure no overlaps
  internal/model/exposure.go
  internal/model/exposure_test.go
Labels: approved, cla: yes, lgtm, size/S

#263 align spec and api implementation.
  docs/server_functional_requirements.md
  internal/android/nonce.go
  internal/android/nonce_test.go
  internal/android/safetynet_test.go
  internal/api/jsonutil/unmarshal_test.go
  internal/model/exposure.go
  internal/verification/verify.go
  tools/exposure-client/main.go
Labels: approved, cla: yes, lgtm, size/L

#268 Fix relative link in docs
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, size/XS

#271 Added test for edge cases of keys aligning with batches.
  internal/database/export_test.go
  internal/database/exposure.go
Labels: approved, cla: yes, lgtm, size/M

#262 Move iOS verification into the database layer
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  config/100-exposure-server.yaml
  internal/database/apiconfig.go
  internal/database/apiconfig_test.go
  internal/database/environment.go
  internal/dbapiconfig/apiconfig.go
  internal/ios/devicecheck.go
  internal/ios/devicecheck_test.go
  internal/secrets/gcp_secret_manager.go
  internal/setup/setup.go
  internal/verification/verify.go
  migrations/000014_ios_per_app_config.down.sql
  migrations/000014_ios_per_app_config.up.sql
  migrations/000015_cts_integ_default.down.sql
  migrations/000015_cts_integ_default.up.sql
  terraform/main.tf
  testdata/config.sql
Labels: approved, cla: yes, lgtm, size/XL

#277 Update cmd names in deployment document
  docs/deploying.md
Labels: approved, cla: yes, lgtm, size/XS

#281 Add an index to exposure.create_at
  migrations/000016_idx_exposure_created_at.down.sql
  migrations/000016_idx_exposure_created_at.up.sql
Labels: approved, cla: yes, lgtm, size/M

#285 Adjust transmission risk range in documentation
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, size/XS

#275 Adjust batch boundary conditions so that published keys hit an open batch
  internal/api/export/worker.go
  internal/database/export_test.go
  internal/database/exposure.go
  internal/database/exposure_test.go
Labels: approved, cla: yes, lgtm, size/M

#286 Propose me as an OWNER
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#283 demonstrate verification key version
  internal/api/export/config.go
  internal/api/export/exportfile.go
  internal/api/export/worker.go
Labels: approved, cla: yes, lgtm, size/M

#282 add sample export file
  examples/export/README.md
  examples/export/public.pem
  examples/export/sample-export.zip
Labels: approved, cla: yes, lgtm, size/M

#288 Make insert export file idempotent by skipping overwrite.
  internal/database/export.go
  internal/database/export_test.go
Labels: approved, cla: yes, lgtm, size/XS

#292 fix misspelling
  internal/api/cleanup/cleanup.go
  internal/api/jsonutil/unmarshal.go
  internal/api/publish/publish.go
  internal/database/exposure.go
  internal/envconfig/envconfig.go
  internal/model/exposure.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#293 Enable vacuum on all tables
  migrations/000017_vacuum.down.sql
  migrations/000017_vacuum.up.sql
Labels: approved, cla: yes, lgtm, size/M

#294 make tranismission risk per-exposure key
  internal/model/exposure.go
  internal/model/exposure_test.go
  tools/exposure-client/main.go
Labels: approved, cla: yes, lgtm, size/M

#278 Clarify the text on signing the 'incremental files' and distributing public keys for this
  README.md
  docs/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#298 Adjust transmissionRisk ranges to match after #294
  docs/server_functional_requirements.md
  internal/model/exposure.go
Labels: approved, cla: yes, lgtm, size/XS

#296 Emit log if conflict on ExportFile insertion (skipping overwrite).
  internal/database/database.go
  internal/database/export.go
  internal/database/export_test.go
Labels: approved, cla: yes, lgtm, size/M

#260 add federation services to terraform config
  builders/build.yaml
  builders/deploy.yaml
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/L

#302 fix typo in tf env vars
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#300 optional cloudbuild triggers and other terraform improvements
  builders/schema.yaml
  terraform/README.md
  terraform/main.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/M

#303 Add federation deployments to deploy.yaml
  builders/deploy.yaml
Labels: approved, cla: yes, lgtm, size/S

#304 ensure a minimum export file length
  internal/api/export/config.go
  internal/api/export/worker.go
  internal/api/export/worker_test.go
  internal/model/exposure.go
  internal/model/exposure_test.go
Labels: approved, cla: yes, lgtm, size/L

#306 Allow at most one index file write for empty batch within worker.
  internal/api/export/worker.go
Labels: approved, cla: yes, lgtm, size/M

#310 have both ways of logging in to gcloud
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/XS

#311 pass through empty batches
  internal/api/export/worker.go
  internal/api/export/worker_test.go
Labels: approved, cla: yes, lgtm, size/S

#308 make truncate window configurable
  internal/api/export/batcher.go
  internal/api/export/batcher_test.go
  internal/api/export/config.go
  internal/api/federationin/config.go
  internal/api/federationin/federationin.go
  internal/api/federationin/federationin_test.go
  internal/api/federationout/config.go
  internal/api/federationout/federationout.go
  internal/api/publish/config.go
  internal/api/publish/publish.go
  internal/model/exposure.go
  internal/model/exposure_test.go
Labels: approved, cla: yes, lgtm, size/M

#299 complete move of transmission risk to per-exposure key
  docs/server_functional_requirements.md
  internal/android/nonce.go
  internal/android/nonce_test.go
  internal/android/safetynet_test.go
  internal/api/jsonutil/unmarshal_test.go
  internal/model/exposure.go
  internal/model/exposure_test.go
Labels: approved, cla: yes, lgtm, size/L

#309 Restructure api directories to be under internal matching package name
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/monolith/main.go
  internal/cleanup/cleanup.go
  internal/cleanup/cleanup_test.go
  internal/cleanup/config.go
  internal/config/config.go
  internal/dbapiconfig/apiconfig.go
  internal/export/batcher.go
  internal/export/batcher_test.go
  internal/export/config.go
  internal/export/exportfile.go
  internal/export/server.go
  internal/export/server_test.go
  internal/export/worker.go
  internal/export/worker_test.go
  internal/federationin/config.go
  internal/federationin/federationin.go
  internal/federationin/federationin_test.go
  internal/federationout/config.go
  internal/federationout/federationout.go
  internal/federationout/federationout_test.go
  internal/handlers/delay.go
  internal/handlers/delay_test.go
  internal/jsonutil/unmarshal.go
  internal/jsonutil/unmarshal_test.go
  internal/publish/config.go
  internal/publish/publish.go
  internal/serverenv/env.go
  tools/federationin-query/main.go
  tools/federationout-authorization/main.go
  tools/federationout-test/main.go
Labels: approved, cla: yes, lgtm, size/M

#317 mark tests helper functions
  internal/database/database_test.go
  internal/export/worker_test.go
  internal/jsonutil/unmarshal_test.go
  internal/model/exposure_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#313 Refactor apiconfig interfaces
  cmd/exposure/main.go
  cmd/monolith/main.go
  internal/android/nonce.go
  internal/android/nonce_test.go
  internal/android/safetynet.go
  internal/android/safetynet_test.go
  internal/apiconfig/config.go
  internal/apiconfig/database_provider.go
  internal/apiconfig/memory_provider.go
  internal/apiconfig/provider.go
  internal/database/apiconfig.go
  internal/database/apiconfig_test.go
  internal/database/config.go
  internal/dbapiconfig/apiconfig.go
  internal/model/apiconfig.go
  internal/model/apiconfig/config.go
  internal/model/apiconfig/config_test.go
  internal/model/apiconfig_test.go
  internal/model/exposure.go
  internal/model/exposure_test.go
  internal/publish/config.go
  internal/publish/publish.go
  internal/serverenv/env.go
  internal/setup/setup.go
  internal/verification/verify.go
  internal/verification/verify_test.go
  migrations/000018_idx_app_package_name.down.sql
  migrations/000018_idx_app_package_name.up.sql
Labels: approved, cla: yes, lgtm, size/XXL

#318 Rename APIConfig to AuthorizedApp
  cmd/monolith/main.go
  internal/android/safetynet.go
  internal/android/safetynet_test.go
  internal/authorizedapp/config.go
  internal/authorizedapp/database_provider.go
  internal/authorizedapp/memory_provider.go
  internal/authorizedapp/provider.go
  internal/database/authorized_app.go
  internal/database/authorized_app_test.go
  internal/database/database_test.go
  internal/model/authorized_app.go
  internal/model/authorized_app_test.go
  internal/model/exposure.go
  internal/publish/config.go
  internal/publish/publish.go
  internal/serverenv/env.go
  internal/setup/setup.go
  internal/verification/verify.go
  internal/verification/verify_test.go
  migrations/000020_rename_apiconfig_to_authorized_app.down.sql
  migrations/000020_rename_apiconfig_to_authorized_app.up.sql
Labels: approved, cla: yes, lgtm, size/L

#314 Add support for Azure KeyVault and HashiCorp Vault interfaces
  go.mod
  go.sum
  internal/secrets/azure_keyvault.go
  internal/secrets/cacher.go
  internal/secrets/cacher_test.go
  internal/secrets/gcp_secret_manager.go
  internal/secrets/hashicorp_vault.go
  internal/secrets/secrets.go
  internal/setup/setup.go
Labels: approved, cla: yes, lgtm, size/XL

#331 Implement filesystem blobstore
  internal/storage/filesystem_storage.go
  internal/storage/filesystem_storage_test.go
  internal/storage/google_cloud_storage.go
Labels: approved, cla: yes, lgtm, size/L

#335 Simplify context done checks
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/S

#336 minor simplifications
  internal/export/batcher_test.go
  internal/export/exportfile.go
  internal/export/server_test.go
  internal/export/worker_test.go
  internal/federationin/federationin.go
  internal/federationout/federationout.go
  internal/federationout/federationout_test.go
Labels: approved, cla: yes, lgtm, size/M

#338 internal/database: defer resetTestDB
  internal/database/authorized_app_test.go
Labels: approved, cla: yes, lgtm, size/XS

#339 default max number of keys should be 15, per e2e testing w/ client team
  internal/publish/config.go
Labels: approved, cla: yes, lgtm, size/XS

#340 Terraform docs move and improvement
  docs/deploying.md
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/L

#344 suppress ko warning, https://github.com/google/ko/issues/160
  .ko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#341 Update Terraform setup from Mike's journey
  .gitignore
  terraform/README.md
  terraform/main.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#301 Allow schema.yaml to work again after changes to docker containers.
  builders/schema.yaml
  docker/migrate.dockerfile
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/S

#343 log effective environment config on startup. Omit DB password
  internal/database/config.go
  internal/setup/setup.go
Labels: approved, cla: yes, lgtm, size/S

#346 Fix up auth, recurring diff
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/S

#348 change federation fields/types
  internal/database/exposure.go
  internal/federationin/federationin.go
  internal/federationin/federationin_test.go
  internal/federationout/federationout.go
  internal/federationout/federationout_test.go
  internal/model/exposure.go
  internal/pb/federation.pb.go
  internal/pb/federation.proto
  migrations/000021_remove_verificaiton_authority_name.down.sql
  migrations/000021_remove_verificaiton_authority_name.up.sql
  tools/federationout-test/main.go
Labels: approved, cla: yes, lgtm, size/L

#347 Combine database and model packages
  internal/android/safetynet.go
  internal/android/safetynet_test.go
  internal/authorizedapp/database_provider.go
  internal/authorizedapp/memory_provider.go
  internal/authorizedapp/provider.go
  internal/database/authorized_app.go
  internal/database/authorized_app_model.go
  internal/database/authorized_app_model_test.go
  internal/database/authorized_app_test.go
  internal/database/export.go
  internal/database/export_model.go
  internal/database/export_test.go
  internal/database/exposure.go
  internal/database/exposure_model.go
  internal/database/exposure_model_test.go
  internal/database/exposure_test.go
  internal/database/federation_model.go
  internal/database/federationin.go
  internal/database/federationin_test.go
  internal/database/federationout.go
  internal/database/federationout_test.go
  internal/export/batcher.go
  internal/export/exportfile.go
  internal/export/worker.go
  internal/export/worker_test.go
  internal/federationin/federationin.go
  internal/federationin/federationin_test.go
  internal/federationout/federationout.go
  internal/federationout/federationout_test.go
  internal/jsonutil/unmarshal_test.go
  internal/publish/publish.go
  internal/verification/verify.go
  internal/verification/verify_test.go
  tools/export-config/main.go
  tools/exposure-client/main.go
  tools/federationin-query/main.go
  tools/federationout-authorization/main.go
Labels: approved, cla: yes, lgtm, size/L

#351 fix locking error in appconfig caching
  internal/authorizedapp/database_provider.go
Labels: approved, cla: yes, lgtm, size/M

#363 Fix typos.
  docs/deploying.md
  docs/server_functional_requirements.md
  internal/android/safetynet.go
  internal/authorizedapp/database_provider.go
  internal/cleanup/cleanup.go
  internal/database/exposure_model.go
  internal/envconfig/envconfig.go
  internal/handlers/delay.go
  internal/jsonutil/unmarshal.go
  internal/metrics/exporter.go
  internal/publish/publish.go
  internal/setup/setup.go
  internal/storage/filesystem_storage.go
  internal/storage/google_cloud_storage.go
  internal/storage/storage.go
  tools/export-config/main.go
  tools/hexconvert/main.go
  tools/unwrap-signature/main.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#364 Lower the spec for Cloud SQL to avoid excessive overprovisioning
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/XS

#356 Use `gcloud run` instead of `gcloud alpha run`
  builders/deploy.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#352 Rename/prefix SafetyNet columns
  internal/android/safetynet.go
  internal/android/safetynet_test.go
  internal/database/authorized_app.go
  internal/database/authorized_app_model.go
  internal/database/authorized_app_test.go
  internal/verification/verify.go
  internal/verification/verify_test.go
  migrations/000022_authorized_app_prefixes.down.sql
  migrations/000022_authorized_app_prefixes.up.sql
  testdata/config.sql
Labels: approved, cla: yes, lgtm, size/L

#366 create debug mode for exposure notifications upload so developers can…
  internal/publish/config.go
  internal/publish/publish.go
  internal/setup/setup.go
  tools/exposure-client/main.go
Labels: approved, cla: yes, lgtm, size/L

#354 Add cleanup-exposure and cleanup-export Terraform configs
  builders/build.yaml
  internal/database/export.go
  terraform/ko.Dockerfile
  terraform/main.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#362 Terraform deployment edits
  docs/deploying.md
Labels: approved, cla: yes, lgtm, size/L

#374 Break apart services into their own files
  terraform/database.tf
  terraform/main.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_export.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/storage.tf
Labels: approved, cla: yes, lgtm, size/XXL

#358 Moving util methods to the enclient lib.
  testing/enclient/enclient.go
  tools/exposure-client/main.go
Labels: approved, cla: yes, lgtm, size/L

#379 regen federation.pb.go, comments are out of date
  internal/pb/federation.pb.go
Labels: approved, cla: yes, lgtm, size/XS

#380 Remove redundant text from README.md and index.md
  README.md
  docs/index.md
Labels: approved, cla: yes, lgtm, size/M

#378 Fixes for issue 252
  internal/database/exposure_model.go
  internal/database/exposure_model_test.go
  internal/export/batcher.go
  internal/export/config.go
  internal/export/server.go
Labels: approved, cla: yes, lgtm, size/S

#383 Remove requirement for DC key_id and team_id to be secrets
  internal/database/authorized_app.go
  internal/database/authorized_app_test.go
  migrations/000023_dc_less_secrets.down.sql
  migrations/000023_dc_less_secrets.up.sql
  testdata/config.sql
Labels: approved, cla: yes, lgtm, size/M

#353 add tool to generate export files
  examples/export/README.md
  examples/export/keys.json
  examples/export/private.pem
  examples/export/public.pem
  examples/export/sample-export.zip
  examples/export/testExport-2-records-1-of-1.zip
  internal/database/exposure_model.go
  internal/database/exposure_model_test.go
  internal/export/exportfile.go
  internal/export/worker.go
  internal/util/generate.go
  testing/enclient/enclient.go
  tools/export-generate/main.go
  tools/exposure-client/main.go
Labels: approved, cla: yes, lgtm, size/XL

#388 IOS Devicecheck edits
  docs/ios_device_check.md
Labels: approved, cla: yes, lgtm, size/L

#389 Use same migrate container as local dev, share subs across build steps
  builders/deploy.yaml
  builders/promote.yaml
  builders/schema.yaml
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/L

#361 Authorized App through interface
  internal/android/safetynet.go
  internal/android/safetynet_test.go
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database/authorized_app_test.go
  internal/authorizedapp/database_provider.go
  internal/authorizedapp/memory_provider.go
  internal/authorizedapp/model/authorized_app_model.go
  internal/authorizedapp/model/authorized_app_model_test.go
  internal/authorizedapp/provider.go
  internal/database/connection.go
  internal/database/database.go
  internal/database/database_test_util.go
  internal/database/export.go
  internal/database/export_test.go
  internal/database/exposure.go
  internal/database/exposure_test.go
  internal/database/federationin.go
  internal/database/federationin_test.go
  internal/database/federationout.go
  internal/database/federationout_test.go
  internal/database/lock_test.go
  internal/pb/federation.pb.go
  internal/verification/verify.go
  internal/verification/verify_test.go
Labels: approved, cla: yes, lgtm, size/L

#390 Add full paths
  examples/export/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#391 Update tek-file documentation
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#392 Add script for running prod migrations
  builders/migrate.yaml
  scripts/migrate
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/L

#393 Allow per-app config of DeviceCheck and SafetyNet
  cmd/exposure/main.go
  docs/ios_device_check.md
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database/authorized_app_test.go
  internal/authorizedapp/model/authorized_app_model.go
  internal/publish/config.go
  internal/publish/publish.go
  migrations/000024_configurable_checks.down.sql
  migrations/000024_configurable_checks.up.sql
  testdata/config.sql
Labels: approved, cla: yes, lgtm, size/L

#396 introduce 'both' as platform option
  internal/authorizedapp/model/authorized_app_model.go
Labels: approved, cla: yes, lgtm, size/S

#398 internal/publish: don't pass a pointer to a pointer to json Unmarshal
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#399 fixed the way to hold http.Client
  internal/ios/devicecheck.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#402 Added missing _REGION substitution for Cloud Build Triggers
  terraform/main.tf
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#394 Separate Export Model and DB
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database/authorized_app_test.go
  internal/authorizedapp/database_provider.go
  internal/cleanup/cleanup.go
  internal/database/database.go
  internal/database/exposure.go
  internal/database/federationin.go
  internal/database/federationout.go
  internal/database/lock.go
  internal/export/batcher.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/exportfile.go
  internal/export/model/export_model.go
  internal/export/worker.go
  tools/export-config/main.go
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, size/L

#408 clarify num-keys and tek-file flag interop
  internal/pb/federation.pb.go
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, size/XS

#409 Use more lenient Content-Type checking
  internal/jsonutil/unmarshal.go
  internal/jsonutil/unmarshal_test.go
Labels: approved, cla: yes, lgtm, size/XS

#397 Filesystem support
  cmd/monolith/main.go
  internal/cleanup/config.go
  internal/export/config.go
  internal/setup/setup.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, size/L

#406 Get Terraform out of the CI/CD business
  .gitignore
  .ko.yaml
  Dockerfile
  builders/build.yaml
  builders/deploy.yaml
  builders/migrate.yaml
  builders/promote.yaml
  docs/deploying.md
  scripts/build
  scripts/deploy
  scripts/promote
  terraform/README.md
  terraform/database.tf
  terraform/main.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_export.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/XL

#411 Ignore name changes on Cloud SQL
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/XS

#410 Separate db/model federation
  internal/authorizedapp/database/authorized_app_test.go
  internal/database/database_test_util.go
  internal/export/database/export_test.go
  internal/federationin/database/federationin.go
  internal/federationin/database/federationin_test.go
  internal/federationin/federationin.go
  internal/federationin/federationin_test.go
  internal/federationin/model/federation_model.go
  internal/federationout/database/federationout.go
  internal/federationout/database/federationout_test.go
  internal/federationout/federationout.go
  internal/publish/database/exposure_test.go
  tools/federationin-query/main.go
  tools/federationout-authorization/main.go
Labels: approved, cla: yes, lgtm, size/L

#395 Admin Console - Implement AuthorizedApps editing
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database/authorized_app_test.go
  internal/authorizedapp/model/authorized_app_model.go
  internal/export/database/export.go
  internal/export/model/export_model.go
  tools/admin-console/authorizedapps.go
  tools/admin-console/authorizedapps_test.go
  tools/admin-console/config.go
  tools/admin-console/index.go
  tools/admin-console/main.go
  tools/admin-console/templates/app_view.html
  tools/admin-console/templates/bottom.html
  tools/admin-console/templates/error.html
  tools/admin-console/templates/index.html
  tools/admin-console/templates/top.html
  tools/admin-console/util.go
Labels: approved, cla: yes, lgtm, size/XL

#416 temporaryTracingKeys is now temporaryExposureKeys
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#417 Fix typo
  internal/android/safetynet.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#418 fixed map allocation in federationout
  internal/federationout/federationout.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#412 add references to the admin console in the docs
  README.md
  docs/deploying.md
  docs/index.md
Labels: approved, cla: yes, lgtm, size/M

#419 Add Vault as a signing option
  go.mod
  go.sum
  internal/signing/gcpkms.go
  internal/signing/hashicorp_vault.go
  internal/signing/hashicorp_vault_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#421 Add tests for Vault secrets
  go.mod
  go.sum
  internal/secrets/hashicorp_vault.go
  internal/secrets/hashicorp_vault_test.go
  internal/signing/hashicorp_vault_test.go
Labels: approved, cla: yes, lgtm, size/L

#424 all: fix all staticcheck warnings
  internal/authorizedapp/database/authorized_app_test.go
  internal/authorizedapp/database_provider.go
  internal/authorizedapp/memory_provider.go
  internal/authorizedapp/model/authorized_app_model.go
  internal/authorizedapp/provider.go
  internal/database/connection.go
  internal/database/database.go
  internal/database/database_test_util.go
  internal/database/iterator.go
  internal/export/exportfile.go
  internal/federationin/database/federationin.go
  internal/federationin/federationin_test.go
  internal/handlers/delay_test.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  internal/storage/storage.go
  testing/enclient/enclient.go
  tools/admin-console/authorizedapps.go
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#428 Fix database tests
  go.mod
  internal/authorizedapp/database/authorized_app_test.go
  internal/database/database_test_util.go
  internal/database/database_util.go
  internal/database/lock_test.go
  internal/export/database/export_test.go
  internal/federationin/database/federationin_test.go
  internal/federationout/database/federationout_test.go
  internal/publish/database/exposure_test.go
  scripts/presubmit.sh
Labels: approved, cla: yes, kind/bug, lgtm, size/XL

#429 Move admin-console to gin framework
  go.mod
  go.sum
  internal/admin/authorizedapps/form.go
  internal/admin/authorizedapps/save.go
  internal/admin/authorizedapps/view.go
  internal/admin/authorizedapps/view_test.go
  internal/admin/config.go
  internal/admin/controller.go
  internal/admin/index/index.go
  internal/admin/util.go
  internal/authorizedapp/database/authorized_app.go
  tools/admin-console/authorizedapps.go
  tools/admin-console/main.go
  tools/admin-console/templates/authorizedapp.html
  tools/admin-console/templates/error.html
  tools/admin-console/templates/index.html
Labels: approved, cla: yes, lgtm, size/XL

#427 unit tests for internal/cleanup
  internal/cleanup/cleanup_test.go
  internal/export/database/export_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#413 all: add distributed tracing with OpenCensus
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/monolith/main.go
  docs/deploying.md
  go.mod
  go.sum
  internal/cleanup/cleanup.go
  internal/federationin/federationin.go
  internal/ios/devicecheck.go
  internal/observability/observability.go
  internal/publish/publish.go
  tools/federationout-test/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#426 Changed timestamp handling in the export-generate tool.
  examples/export/testExport-2-records-1-of-1.zip
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#435 Adds Admin Console for Signature Info
  internal/admin/index/index.go
  internal/admin/siginfo/form.go
  internal/admin/siginfo/save.go
  internal/admin/siginfo/view.go
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database/authorized_app_test.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/model/export_model.go
  tools/admin-console/main.go
  tools/admin-console/templates/index.html
  tools/admin-console/templates/siginfo.html
  tools/admin-console/templates/top.html
Labels: approved, cla: yes, lgtm, size/XL

#439 Update and fix missing docs
  config/100-exposure-server.yaml
  docker/ko.dockerfile
  docs/deploying.md
Labels: approved, cla: yes, lgtm, size/L

#440 ci: reenable go vet
  internal/federationin/federationin.go
  internal/federationout/federationout_test.go
  scripts/presubmit.sh
  tools/federationout-test/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#441 Break Monolith's realMain into an importable utility method for testing.
  cmd/monolith/main.go
  internal/monolith/monolith_util.go
Labels: approved, cla: yes, lgtm, size/L

#442 clarify verification key fields
  internal/pb/export/export.pb.go
  internal/pb/export/export.proto
Labels: approved, cla: yes, lgtm, size/XS

#444 Cleanup issue templates, close stale
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature..md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/stale.yaml
  .prow/images/exposure-notifications-test/Makefile
  docker/presubmit-test.dockerfile
Labels: approved, cla: yes, lgtm, size/L

#446 Rename stale.yaml to stale.yml
  .github/workflows/stale.yml
Labels: approved, cla: yes, lgtm, size/XS

#448 Use correct default SSL mode
  internal/database/config.go
Labels: approved, cla: yes, lgtm, size/XS

#415 Adding method for extracting keys from the export file.
  internal/export/exportfile.go
  internal/export/exportfile_test.go
Labels: approved, cla: yes, lgtm, size/L

#451 add deployable service to generate data
  cmd/generate/main.go
  internal/generate/config.go
  internal/generate/handler.go
  internal/util/generate.go
  tools/export-generate/main.go
  tools/exposure-client/main.go
Labels: approved, cla: yes, lgtm, size/L

#452 Fixing outdated comments.
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/XS

#458 Doc changes as docs/ is deployed self contained
  docs/deploying.md
  docs/index.md
Labels: approved, cla: yes, lgtm, size/S

#456 Add optional deployment of generate service
  docs/deploying.md
  scripts/build
  scripts/deploy
  scripts/promote
  terraform/README.md
  terraform/service_generate.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#457 fix issues with index file
  internal/export/config.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/S

#462 proto: use full package path in go_option
  internal/pb/export/export.pb.go
  internal/pb/export/export.proto
  internal/pb/federation.pb.go
  internal/pb/federation.proto
  scripts/dev
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#463 clarify batch field usage for iOS
  internal/pb/export/export.pb.go
  internal/pb/export/export.proto
Labels: approved, cla: yes, lgtm, size/XS

#464 Don't use magical "default" network
  terraform/database.tf
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/S

#461 Update contribution docs
  CONTRIBUTING.md
  internal/database/database_util.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#455 Adding tool to read content of export files.
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/M

#467 remove OCA
  go.mod
  go.sum
  internal/observability/observability.go
Labels: approved, cla: yes, lgtm, size/S

#465 Exports from multiple regions
  internal/admin/authorizedapps/form.go
  internal/admin/exports/form.go
  internal/admin/exports/view_test.go
  internal/export/batcher.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/exportfile.go
  internal/export/exportfile_test.go
  internal/export/model/export_model.go
  internal/export/model/export_model_test.go
  internal/export/worker.go
  migrations/000025_multiple_region_exports.down.sql
  migrations/000025_multiple_region_exports.up.sql
  tools/admin-console/templates/export.html
  tools/admin-console/templates/index.html
  tools/export-config/main.go
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, size/L

#468 Add cleanup for Container Registry
  terraform/service_gcr_cleaner.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#472 Drop Cloud SQL proxy and switch to VPC connections
  terraform/database.tf
  terraform/key_management.tf
  terraform/main.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_export.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_gcr_cleaner.tf
  terraform/service_generate.tf
Labels: approved, cla: yes, lgtm, size/L

#473 Update contribution instructions
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#474 for e2e testing, allow acceptance of keys valid till the end of the U…
  internal/generate/handler.go
  internal/publish/config.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/M

#475 docs: Update diagram verbiage
  docs/diagrams/google_cloud_run.diagram
  docs/diagrams/google_cloud_run.svg
  docs/images/google_cloud_run.png
Labels: approved, cla: yes, lgtm, size/L

#470 first draft of verification design doc
  docs/design/verification_protocol.md
Labels: approved, cla: yes, lgtm, size/L

#477 Return the created MonoConfig.
  cmd/monolith/main.go
  internal/monolith/monolith_util.go
Labels: approved, cla: yes, lgtm, size/S

#479 observability: bring back ocagent after updating to v0.0.7
  go.mod
  go.sum
  internal/observability/observability.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#483 check inbound platform in addition to authorizedapp settings
  internal/authorizedapp/model/authorized_app_model.go
  internal/publish/model/exposure_model.go
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/M

#486 Export bucket is not used, remove it
  internal/export/database/export.go
  terraform/service_export.tf
Labels: approved, cla: yes, lgtm, size/XS

#487 Allow per-service overrides
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_export.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/M

#478 add shared API definitions for PHA verification protocol
  pkg/api/v1alpha1/verification_types.go
  pkg/api/v1alpha1/verification_types_test.go
Labels: approved, cla: yes, lgtm, size/M

#488 Allow per-service location customization
  .gitignore
  terraform/README.md
  terraform/database.tf
  terraform/key_management.tf
  terraform/main.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_export.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_gcr_cleaner.tf
  terraform/service_generate.tf
  terraform/storage.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#492 Support runtime configuration of all current components
  docs/deploying.md
  internal/admin/config.go
  internal/cleanup/config.go
  internal/export/config.go
  internal/export/server_test.go
  internal/federationin/config.go
  internal/federationout/config.go
  internal/generate/config.go
  internal/monolith/monolith_util.go
  internal/observability/observability.go
  internal/publish/config.go
  internal/secrets/cacher.go
  internal/secrets/cacher_test.go
  internal/secrets/google_secret_manager.go
  internal/secrets/secrets.go
  internal/setup/setup.go
  internal/signing/google_cloud_kms.go
  internal/signing/signing.go
  internal/storage/noop_storage.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, size/XL

#494 don't cache the export index
  internal/export/worker.go
  internal/storage/filesystem_storage.go
  internal/storage/filesystem_storage_test.go
  internal/storage/google_cloud_storage.go
  internal/storage/noop_storage.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, size/S

#493 implement verification and processing of health authority diagnosis v…
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database/authorized_app_test.go
  internal/authorizedapp/model/authorized_app_model.go
  internal/database/database.go
  internal/export/database/export.go
  internal/publish/model/exposure_model.go
  internal/verification/database/health_authority_db.go
  internal/verification/database/health_authority_db_test.go
  internal/verification/model/health_authority.go
  internal/verification/model/health_authority_test.go
  internal/verification/phaverify.go
  internal/verification/phaverify_test.go
  migrations/000026_health_authority_config.down.sql
  migrations/000026_health_authority_config.up.sql
  pkg/api/v1alpha1/verification_types.go
  pkg/verification/utils.go
  pkg/verification/utils_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#499 Fix nil pointer on environment setup.
  internal/admin/config.go
  internal/cleanup/config.go
  internal/export/config.go
  internal/federationin/config.go
  internal/federationout/config.go
  internal/generate/config.go
  internal/monolith/monolith_util.go
  internal/publish/config.go
  internal/setup/setup.go
Labels: approved, cla: yes, lgtm, size/L

#500 Document why we process the envconfig
  internal/setup/setup.go
Labels: approved, cla: yes, lgtm, size/XS

#501 add health authority certificate bypass option to authorized app
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database/authorized_app_test.go
  internal/authorizedapp/model/authorized_app_model.go
  migrations/000027_add_authoried_app_require_pha.down.sql
  migrations/000027_add_authoried_app_require_pha.up.sql
Labels: approved, cla: yes, lgtm, size/M

#498 Fix linting errors from experiment
  internal/admin/authorizedapps/save.go
  internal/admin/authorizedapps/view.go
  internal/admin/config.go
  internal/admin/controller.go
  internal/admin/exports/save.go
  internal/admin/exports/view.go
  internal/admin/index/index.go
  internal/admin/siginfo/save.go
  internal/admin/siginfo/view.go
  internal/android/safetynet.go
  internal/android/safetynet_test.go
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/model/authorized_app_model.go
  internal/database/connection.go
  internal/database/database_util.go
  internal/export/batcher.go
  internal/export/batcher_test.go
  internal/export/config.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/exportfile.go
  internal/export/exportfile_test.go
  internal/export/model/export_model.go
  internal/export/worker.go
  internal/federationin/federationin.go
  internal/generate/handler.go
  internal/publish/database/exposure_test.go
  internal/publish/model/exposure_model.go
  internal/publish/publish.go
  internal/secrets/azure_keyvault.go
  internal/signing/hashicorp_vault.go
  internal/signing/signing.go
  internal/storage/google_cloud_storage.go
  internal/util/generate.go
  internal/verification/database/health_authority_db_test.go
  internal/verification/model/health_authority.go
  internal/verification/model/health_authority_test.go
  pkg/api/v1alpha1/verification_types.go
  pkg/api/v1alpha1/verification_types_test.go
  pkg/verification/utils.go
  testing/enclient/enclient.go
  tools/admin-console/main.go
  tools/export-generate/main.go
  tools/unwrap-signature/main.go
Labels: approved, cla: yes, lgtm, size/L

#469 ci: stop formatting generated files
  internal/pb/export/export.pb.go
  internal/pb/federation.pb.go
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#503 Provide a way to return config from the test database
  internal/database/database_util.go
Labels: approved, cla: yes, lgtm, size/S

#506 Revert "ci: stop formatting generated files"
  internal/pb/export/export.pb.go
  internal/pb/federation.pb.go
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/M

#504 Add tests for setup
  internal/setup/setup_test.go
Labels: approved, cla: yes, lgtm, size/L

#480 Adding clear-export sql script
  scripts/dev
  testdata/clear-export.sql
Labels: approved, cla: yes, lgtm, size/S
