Repository google/exposure-notifications-server, pull requests merged in 2020-12, with the labels that each got.

#1201 Adjust latency alert threshold
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/M

#1203 update deps
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#1189 index processing guidelines
  docs/getting-started/downloading-export-batches-keys.md
Labels: approved, cla: yes, lgtm, size/M

#1204 Integration test add scenario of more than 1 exported files
  internal/integration/helpers.go
  internal/integration/integration_test.go
Labels: approved, cla: yes, lgtm, size/L

#1206 Remove bogus provider configs.
  terraform/alerting/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1207 Fix the MQL query, remove group by type.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1209 remove batchnum/batchsize construct
  internal/export/exportfile.go
  internal/export/exportfile_test.go
  internal/export/worker.go
  internal/export/worker_test.go
  internal/pb/export/export.proto
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, size/M

#1208 Unit test testing large batch exports
  internal/export/worker_test.go
Labels: approved, cla: yes, lgtm, size/L

#1210 Add unit tests for mirror service
  internal/admin/mirrors/form.go
  internal/mirror/config.go
  internal/mirror/database/mirror.go
  internal/mirror/file_status.go
  internal/mirror/file_status_test.go
  internal/mirror/mirror.go
  internal/mirror/mirror_test.go
  internal/mirror/model/mirror.go
  internal/mirror/model/mirror_test.go
  internal/mirror/server.go
  internal/mirror/server_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1211 add tool to visualize links in an export file
  tools/export-viz/main.go
Labels: approved, cla: yes, lgtm, size/L

#1212 Increase p50 on cleanup-export to 60s
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1215 allow for max records to be overridden on a per-export-config basis
  internal/admin/exports/form.go
  internal/export/batcher.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/model/export_model.go
  internal/export/model/export_model_test.go
  internal/export/worker.go
  internal/export/worker_test.go
  migrations/000053_AddMaxRecordsOverride.down.sql
  migrations/000053_AddMaxRecordsOverride.up.sql
  tools/admin-console/templates/export.html
Labels: approved, cla: yes, lgtm, size/L

#1216 Nit: kebab-case for html names
  internal/admin/authorizedapps/form.go
  internal/admin/exportimporters/form.go
  internal/admin/exports/form.go
  internal/admin/healthauthority/form.go
  internal/admin/mirrors/form.go
  internal/admin/siginfo/form.go
  tools/admin-console/templates/authorizedapp.html
  tools/admin-console/templates/export-importer.html
  tools/admin-console/templates/export.html
  tools/admin-console/templates/healthauthority.html
  tools/admin-console/templates/mirror.html
  tools/admin-console/templates/siginfo.html
Labels: approved, cla: yes, lgtm, size/L

#1217 make data padding more better
  internal/export/worker.go
  internal/export/worker_test.go
Labels: approved, cla: yes, lgtm, size/M

#1218 don't stop retrying azure credential refresh on single failure
  internal/storage/azure_blobstore.go
  pkg/signal/signal.go
Labels: approved, cla: yes, lgtm, size/M

#1220 Bump export service to 2G RAM
  terraform/service_export.tf
Labels: approved, cla: yes, lgtm, size/XS

#1221 Add initial Cloud Armor config to Terraform.
  terraform/dos.tf
  terraform/service_debugger.tf
  terraform/service_exposure.tf
  terraform/service_federationout.tf
Labels: approved, cla: yes, lgtm, size/L

#1225 deflake test
  internal/export/worker_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1222 Playbooks for alerts
  docs/playbooks/alerts/LatencyTooHigh.md
  docs/playbooks/playbook_test.go
  go.mod
  go.sum
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/L

#1224 Use proper unit and avoid converting between units.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/S

#1227 Terraform: VPC connector depends on service networking connection
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1228 Fix typo
  internal/export/worker.go
  internal/exportimport/import.go
  internal/federationin/federationin.go
  internal/publish/database/exposure.go
Labels: approved, cla: yes, lgtm, size/S

#1230 additional data defaults when importing keys from export files
  internal/exportimport/config.go
  internal/exportimport/import.go
  internal/exportimport/server.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
Labels: approved, cla: yes, lgtm, size/L

#1231 Use a duration literal to specify the thresholds.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/S

#1233 Change Cloud Armor to preview only.
  terraform/dos.tf
Labels: approved, cla: yes, lgtm, size/XS

#1234 Exclude a rule in Cloud Armor.
  terraform/dos.tf
Labels: approved, cla: yes, lgtm, size/S

#1226 Remove the reference to the metrics middleware.
  internal/cleanup/cleanup.go
  internal/export/batcher.go
  internal/export/worker.go
  internal/federationin/federationin.go
  internal/federationin/federationin_test.go
  internal/federationout/federationout.go
  internal/keyrotation/rotate.go
  internal/publish/publish.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
Labels: approved, cla: yes, lgtm, size/L

#1235 Add a knob to enable Load Balancer logging.
  terraform/service_debugger.tf
  terraform/service_exposure.tf
  terraform/service_federationout.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/S

#1237 Add linters for Terraform
  .github/workflows/terraform.yml
  terraform/alerting/variables.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/M

#1238 Upgrade terraform to 0.14.2 in presubmit test image
  docker/presubmit-test.dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1239 Adjust Stackdriver export timeout to 1 minute.
  pkg/observability/config.go
Labels: approved, cla: yes, lgtm, size/XS

#1241 Update notification channel setting in key server.
  terraform/alerting/alerts.tf
  terraform/alerting/notifications.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#1242 Update google provider to 3.51
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/XS

#1244 Add terraform lock to source control
  terraform-e2e-ci/.terraform.lock.hcl
Labels: approved, cla: yes, lgtm, size/M

#1245 Terraform destroy first remove database from state
  scripts/ci-terraform.sh
Labels: approved, cla: yes, lgtm, size/XS

#1246 Update deps
  go.mod
  go.sum
  internal/storage/azure_blobstore.go
Labels: approved, cla: yes, lgtm, size/XL

#1248 Terraform: add hash from CI runner
  scripts/ci-terraform.sh
  terraform-e2e-ci/.terraform.lock.hcl
Labels: approved, cla: yes, lgtm, size/XS

#1243 Update google provider to 3.51
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/XS

#1249 Fix typo in docs
  docs/design/verification_protocol.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1251 Metrics
  internal/exportimport/import.go
  internal/federationin/federationin_test.go
  internal/generate/handler.go
  internal/publish/database/exposure.go
  internal/publish/database/stats.go
  internal/publish/database/stats_test.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/model/stats.go
  internal/publish/model/stats_test.go
  internal/publish/platform.go
  internal/publish/platform_test.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
  migrations/000054_HealthAuthorityStats.down.sql
  migrations/000054_HealthAuthorityStats.up.sql
Labels: approved, cla: yes, lgtm, size/XL

#1252 Do not sample logs in production
  pkg/logging/logger.go
Labels: approved, cla: yes, lgtm, size/XS

#1240 Do not ignore annotation changes
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_export_importer.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/service_jwks.tf
  terraform/service_keyrotation.tf
  terraform/service_mirror.tf
Labels: approved, cla: yes, lgtm, size/M

#1254 Add zapw and bodyclose
  .github/workflows/codereview.yaml
  Makefile
  go.mod
  go.sum
  internal/export/worker.go
  scripts/presubmit.sh
  tools/tools.go
Labels: approved, cla: yes, lgtm, size/M

#1255 Improve control over logging package
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/debugger/main.go
  cmd/export-importer/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/generate/main.go
  cmd/jwks-updater/main.go
  cmd/key-rotation/main.go
  cmd/migrate/main.go
  cmd/mirror/main.go
  docs/getting-started/development.md
  internal/publish/publish_test.go
  pkg/logging/logger.go
  pkg/logging/logger_test.go
  terraform-e2e-ci/main.tf
  tools/seed/main.go
  tools/sign/main.go
  tools/verify/main.go
Labels: approved, cla: yes, lgtm, size/L

#1256 Match owners to the team membership
  OWNERS
  docs/OWNERS
  terraform/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#1258 Revert back to old owners
  OWNERS
Labels: cla: yes, lgtm, size/S
