Repository google/exposure-notifications-server, pull requests merged in 2020-06, with the labels that each got.

#508 Hook up health authority verification certificate validation
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/verification/phaverify_test.go
  pkg/api/v1alpha1/verification_types.go
Labels: approved, cla: yes, lgtm, size/XXL

#511 Enable to use scripts/presubmit.sh as a pre-push git hook
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#512 Use noops in tests to avoid credential lookup
  docs/deploying.md
  internal/cleanup/cleanup_test.go
  internal/secrets/noop.go
  internal/secrets/secrets.go
  internal/setup/setup_test.go
  internal/signing/noop.go
  internal/signing/signing.go
  internal/storage/noop.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, size/L

#515 Add support for AWS Secret Manager
  docs/deploying.md
  go.mod
  internal/secrets/aws_secrets_manager.go
  internal/secrets/secrets.go
Labels: approved, cla: yes, lgtm, size/L

#517 Add AWS S3 blobstore
  internal/storage/aws_s3.go
  internal/storage/google_cloud_storage.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, size/M

#518 plugged aws-s3 adapter
  docs/deploying.md
  internal/storage/aws_s3.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#522 Add additional language to server requirement document
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, size/S

#519 Add Azure Blobstore implementation
  docs/deploying.md
  go.mod
  go.sum
  internal/storage/azure_blobstore.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, size/L

#523 fix bug in envconfig where all secrets are processed before the secre…
  internal/setup/setup.go
Labels: approved, cla: yes, lgtm, size/XS

#524 let setups tests pass if you have any secret:// in your env
  internal/setup/setup_test.go
Labels: approved, cla: yes, lgtm, size/S

#527 Add Azure KeyVault signing support
  go.mod
  internal/signing/azure_keyvault.go
Labels: approved, cla: yes, lgtm, size/L

#528 Does this make CI run faster?
  internal/cleanup/cleanup_test.go
  internal/database/database_util.go
  internal/retry/retry.go
  internal/verification/phaverify_test.go
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/L

#509 ci: stop formatting generated files
  internal/pb/export/export.pb.go
  internal/pb/federation.pb.go
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#531 Added path to export.proto
  examples/export/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#534 Marked unused fetchType as deprecated in the federation proto.
  internal/pb/federation.pb.go
  internal/pb/federation.proto
Labels: approved, cla: yes, lgtm, size/L

#533 Revert "ci: stop formatting generated files"
  internal/pb/export/export.pb.go
  internal/pb/federation.pb.go
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/M

#535 increase padding test size. prow test environment has less entropy (i…
  internal/export/worker_test.go
Labels: approved, cla: yes, lgtm, size/XS

#536 Fix bypass HA certificate. Wasn't setting field in form.
  internal/admin/authorizedapps/form.go
Labels: approved, cla: yes, lgtm, size/XS

#538 Ensure that repeated fields end up as empty arrays in DB and not arra…
  internal/admin/authorizedapps/form.go
  internal/admin/exports/form.go
Labels: approved, cla: yes, lgtm, size/S

#539 [master] Fix spelling errors
  internal/publish/model/exposure_model.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#541 Make AppPackageName and BundleID case-insensitive
  docs/server_functional_requirements.md
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database/authorized_app_test.go
  internal/authorizedapp/database_provider.go
  internal/authorizedapp/memory_provider.go
  internal/authorizedapp/provider.go
  internal/export/database/export.go
  internal/publish/database/exposure.go
  migrations/000028_drop_devicecheck_and_safetynet.down.sql
  migrations/000029_lowercase_app_package_names.down.sql
  migrations/000029_lowercase_app_package_names.up.sql
Labels: approved, cla: yes, lgtm, size/L

#532 refactor API definitions to PKG instead of internal so they can be in…
  internal/export/worker.go
  internal/export/worker_test.go
  internal/federationin/federationin.go
  internal/generate/handler.go
  internal/jsonutil/unmarshal_test.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/util/generate.go
  internal/verification/phaverify.go
  internal/verification/phaverify_test.go
  pkg/api/v1alpha1/exposure_types.go
  pkg/verification/utils.go
  pkg/verification/utils_test.go
  testing/enclient/enclient.go
  tools/export-generate/main.go
  tools/exposure-client/main.go
Labels: approved, cla: yes, lgtm, size/L

#548 Update functional requirements
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, size/M

#550 Accept, but embargo currently valid keys
  internal/generate/handler.go
  internal/publish/config.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, size/L, ¯\_(ツ)_/¯

#553 Fix reference to verification_protocol.md
  docs/index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#554 Move monolith into tools
  CONTRIBUTING.md
  tools/monolith/main.go
Labels: approved, cla: yes, lgtm, size/XS

#552 Enable cloudresourcemanager.googleapis.com in Terraform
  terraform/main.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/XS

#551 Gracefully stop servers on interrupt
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/generate/main.go
  internal/interrupt/context.go
  internal/interrupt/interrupt.go
  internal/monolith/monolith.go
  internal/server/server.go
  tools/monolith/main.go
Labels: approved, cla: yes, lgtm, size/L

#557 Factor out cache implementation to standalone package.
  internal/authorizedapp/database_provider.go
  internal/cache/cache.go
  internal/cache/cache_test.go
Labels: approved, cla: yes, lgtm, size/L

#559 Minor changes to support e2e testing
  internal/authorizedapp/database_provider.go
  internal/authorizedapp/memory_provider.go
  internal/authorizedapp/provider.go
  internal/database/database_util.go
  internal/server/server.go
  internal/storage/config.go
  internal/storage/memory.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, size/L

#561 Add initial e2e framework
  internal/integration/integration_test.go
  internal/integration/publish_test.go
Labels: approved, cla: yes, lgtm, size/L

#521 Removing time window used by worker to query for exposure batches available for export.
  internal/export/database/export.go
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/S

#563 Add Navigation, theming, for docs
  docs/.gitignore
  docs/Gemfile
  docs/_config.yml
  docs/_data/navigation.yml
  docs/_layouts/default.html
  docs/deploying.md
  docs/design/verification_protocol.md
  docs/index.md
  docs/server_deployment_options.md
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, size/L

#562 remove app_bundle_id & android_package in SigInfo
  internal/admin/siginfo/form.go
  internal/export/database/export.go
  internal/export/exportfile.go
  internal/export/model/export_model.go
  internal/integration/publish_test.go
  internal/pb/export/export.pb.go
  internal/pb/export/export.proto
  migrations/000030_remove_package_and_bundle.down.sql
  migrations/000030_remove_package_and_bundle.up.sql
  tools/admin-console/templates/siginfo.html
  tools/export-config/main.go
Labels: approved, cla: yes, lgtm, size/L

#560 Move to single cache impl.
  internal/cache/cache.go
  internal/cache/cache_test.go
  internal/publish/config.go
  internal/publish/publish.go
  internal/secrets/cacher.go
  internal/secrets/cacher_test.go
  internal/setup/setup.go
  internal/verification/config.go
  internal/verification/phaverify.go
  internal/verification/phaverify_test.go
Labels: approved, cla: yes, lgtm, size/L

#566 Remove min latency handler from integ
  internal/integration/integration_test.go
Labels: approved, cla: yes, lgtm, size/XS

#567 Remove monolith
  internal/monolith/config.go
  internal/monolith/monolith.go
  tools/monolith/main.go
Labels: approved, cla: yes, lgtm, size/L

#565 Add interfaces for getting objects via the blobstore
  internal/integration/publish_test.go
  internal/storage/aws_s3.go
  internal/storage/azure_blobstore.go
  internal/storage/filesystem_storage.go
  internal/storage/filesystem_storage_test.go
  internal/storage/google_cloud_storage.go
  internal/storage/memory.go
  internal/storage/noop.go
  internal/storage/storage.go
Labels: approved, cla: yes, lgtm, size/L

#568 Add security policy
  .github/SECURITY.md
Labels: approved, cla: yes, lgtm, size/XS

#569 [master] Fix spelling errors
  internal/cache/cache.go
  internal/cache/cache_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS, ¯\_(ツ)_/¯

#570 Switch to git-sha based deployments
  scripts/build
  scripts/deploy
Labels: approved, cla: yes, lgtm, size/S

#571 Update envconfig to fix nested struct passing mutator funcs
  go.mod
  go.sum
  internal/database/connection.go
  internal/setup/setup.go
  internal/setup/setup_test.go
  scripts/deploy
Labels: approved, cla: yes, lgtm, size/M

#572 Use correct generate variable in Terraform
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/XS

#574 Don't log passwords
  internal/database/config.go
  internal/setup/setup.go
Labels: approved, cla: yes, lgtm, size/S

#577 Fix data race in setup tests
  internal/setup/setup_test.go
Labels: approved, cla: yes, lgtm, size/S

#576 Update deploy docs to note git-sha
  docs/deploying.md
Labels: approved, cla: yes, lgtm, size/XS

#575 Remove unused db struct tags
  internal/export/model/export_model.go
  internal/federationin/model/federation_model.go
  internal/publish/model/exposure_model.go
Labels: approved, cla: yes, lgtm, size/L

#558 fix(signing): add configuration option for azure key vault
  internal/signing/config.go
  internal/signing/signing.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#573 Add documentation for publishing, retrieving keys.
  CONTRIBUTING.md
  docs/_data/navigation.yml
  docs/_includes/getting-started-prerequisites.md
  docs/_layouts/default.html
  docs/getting-started/deploying.md
  docs/getting-started/publishing-temporary-exposure-keys.md
  docs/images/admin_console_add_authorized_application.png
  docs/images/admin_console_create_new_export_config.png
  docs/images/admin_console_create_new_health_authority.png
  docs/images/admin_console_create_new_signature_info.png
  docs/images/admin_console_landing.png
  docs/index.md
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/M

#505 Fixed ambiguity in docs, regarding batch generation.
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#582 README.md should link out to docsite
  README.md
  docs/_data/navigation.yml
  docs/getting-started/downloading-export-batches-keys.md
Labels: approved, cla: yes, lgtm, size/M

#583 Address links not building relative for docs
  docs/_config.yml
  docs/_layouts/default.html
Labels: approved, cla: yes, lgtm, size/XS

#585 Add keyvault specific authorizer for Azure signing client
  go.mod
  internal/azurekeyvault/authorizer.go
  internal/secrets/azure_keyvault.go
  internal/signing/azure_keyvault.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#610 Add comments around aud specification.
  docs/design/verification_protocol.md
  tools/admin-console/templates/healthauthority.html
Labels: approved, cla: yes, lgtm, size/S

#611 clarify what is logged
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/XS

#612 point to new link for file format
  docs/server_functional_requirements.md
  examples/export/README.md
Labels: approved, cla: yes, lgtm, size/XS

#615 Specify fields req'd for verification in functional requirements
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, size/XS

#616 URL encode database passwords
  builders/migrate.yaml
  docker/migrate.dockerfile
  docker/urlencode
Labels: approved, cla: yes, lgtm, size/M

#614 Reduce function arity
  internal/federationin/federationin.go
  internal/federationin/federationin_test.go
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, size/L

#617 Fix folder where urlencode lives to fix build script
  docker/migrate.dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#618 Avoid dividing by 0
  internal/export/model/export_model.go
Labels: approved, cla: yes, lgtm, size/XS

#619 Update verification flow doc
  docs/design/verification_protocol.md
Labels: approved, cla: yes, lgtm, size/S

#620 Don't stale privacy bugs
  .github/workflows/stale.yml
Labels: approved, cla: yes, lgtm, size/XS

#621 Export handlers cleanup
  cmd/export/main.go
  internal/database/config.go
  internal/export/batcher.go
  internal/export/database/export.go
  internal/export/server.go
  internal/export/server_test.go
  internal/export/worker.go
  internal/integration/integration_test.go
Labels: approved, cla: yes, lgtm, size/L

#624 Add links to API Definitions to docs
  README.md
  docs/_data/navigation.yml
  docs/index.md
Labels: approved, cla: yes, lgtm, size/S

#625 Add debugger
  cmd/debugger/main.go
  go.mod
  go.sum
  internal/admin/index/index.go
  internal/authorizedapp/database/authorized_app.go
  internal/debugger/config.go
  internal/debugger/debugger.go
  internal/debugger/handler_debug.go
  internal/debugger/server.go
  internal/export/database/export.go
  internal/integration/publish_test.go
  scripts/build
  terraform/main.tf
  terraform/service_debugger.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/XL

#604 include end time in export filenames
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/XS

#628 move cache and base64utils to pkg so they can be imported into verifi…
  internal/authorizedapp/database_provider.go
  internal/publish/database/exposure.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish_test.go
  internal/secrets/cacher.go
  internal/signing/azure_keyvault.go
  internal/signing/hashicorp_vault.go
  internal/util/generate.go
  internal/verification/phaverify.go
  pkg/base64util/decode.go
  pkg/base64util/decode_test.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
Labels: approved, cla: yes, lgtm, size/S

#629 package comments
  pkg/base64util/decode.go
  pkg/cache/cache.go
  pkg/verification/utils.go
Labels: approved, cla: yes, lgtm, size/S

#630 Read all of stdin in urlencode
  docker/urlencode
Labels: approved, cla: yes, lgtm, size/XS

#626 Handle null output region
  internal/database/database_util.go
  internal/export/database/export.go
Labels: approved, cla: yes, lgtm, size/S

#631 move retry to pkg
  internal/database/database_util.go
  pkg/retry/retry.go
Labels: approved, cla: yes, lgtm, size/XS

#634 add ability to expose metrics from /metrics endpoint
  docs/getting-started/deploying.md
  go.mod
  go.sum
  internal/observability/observability.go
  internal/server/metrics.go
  internal/server/server.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#633 Docs for Estimating Costs
  docs/_data/navigation.yml
  docs/getting-started/estimating-costs.md
Labels: approved, cla: yes, lgtm, size/L

#637 Adjust wrapping for note callouts
  docs/getting-started/estimating-costs.md
Labels: approved, cla: yes, lgtm, size/S

#638 #635 export-create-batches creating an empty index file
  internal/export/database/export.go
Labels: approved, cla: yes, lgtm, size/XS

#599 Adding Publish - Export integration test.
  internal/integration/en_api.go
  internal/integration/integration_test.go
  internal/integration/publish_test.go
Labels: approved, cla: yes, lgtm, size/L

#644 Added variable for vpc_access_connector max_throughput
  terraform/main.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#641 feat(observability): use envconfig to manage configuration for the observability exporter
  internal/cleanup/config.go
  internal/export/config.go
  internal/federationin/config.go
  internal/federationout/config.go
  internal/generate/config.go
  internal/observability/config.go
  internal/observability/generic.go
  internal/observability/noop.go
  internal/observability/observability.go
  internal/publish/config.go
  internal/serverenv/env.go
  internal/setup/setup.go
  internal/setup/setup_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#645 Make secrets and key management public
  internal/admin/config.go
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database_provider.go
  internal/cleanup/config.go
  internal/debugger/config.go
  internal/export/config.go
  internal/export/server_test.go
  internal/federationin/config.go
  internal/federationout/config.go
  internal/generate/config.go
  internal/integration/integration_test.go
  internal/publish/config.go
  internal/serverenv/env.go
  internal/setup/setup.go
  internal/setup/setup_test.go
  pkg/keys/aws_kms.go
  pkg/keys/azure_keyvault.go
  pkg/keys/config.go
  pkg/keys/google_cloud_kms.go
  pkg/keys/hashicorp_vault.go
  pkg/keys/hashicorp_vault_test.go
  pkg/keys/keys.go
  pkg/keys/noop.go
  pkg/secrets/aws_secrets_manager.go
  pkg/secrets/azure_keyvault.go
  pkg/secrets/cacher.go
  pkg/secrets/cacher_test.go
  pkg/secrets/config.go
  pkg/secrets/google_secret_manager.go
  pkg/secrets/hashicorp_vault.go
  pkg/secrets/hashicorp_vault_test.go
  pkg/secrets/noop.go
  pkg/secrets/resolver.go
  pkg/secrets/secrets.go
  tools/example-verification-signing/main.go
Labels: approved, cla: yes, lgtm, size/L

#649 Remove latency delay and return real responses
  cmd/exposure/main.go
  internal/handlers/delay.go
  internal/handlers/delay_test.go
  internal/integration/integration_test.go
  internal/publish/config.go
  internal/publish/publish.go
  internal/publish/publish_test.go
Labels: approved, cla: yes, lgtm, size/L

#651 Use correct syntax for default
  internal/observability/config.go
Labels: approved, cla: yes, lgtm, size/XS

#647 Adding integration test for cleanup published exposures
  internal/cleanup/cleanup.go
  internal/integration/en_api.go
  internal/integration/integration_test.go
  internal/integration/publish_test.go
  internal/publish/database/exposure.go
  internal/publish/database/exposure_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#656 Use KeyVault SDK authorizer, which is more flexible
  go.mod
  internal/azurekeyvault/authorizer.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#657 Return error from secret cacher
  pkg/secrets/cacher.go
Labels: approved, cla: yes, lgtm, size/XS

#658 Change key terminology to be more consistent
  README.md
  docs/_config.yml
  docs/design/verification_protocol.md
  docs/diagrams/compute_data_in.diagram
  docs/diagrams/compute_data_in.svg
  docs/diagrams/compute_data_out.diagram
  docs/diagrams/compute_data_out.svg
  docs/diagrams/google_cloud_run.diagram
  docs/diagrams/google_cloud_run.svg
  docs/diagrams/hybrid-in.diagram
  docs/diagrams/hybrid-in.svg
  docs/diagrams/hybrid-out.diagram
  docs/diagrams/hybrid-out.svg
  docs/diagrams/on_prem.diagram
  docs/diagrams/on_prem.svg
  docs/getting-started/deploying.md
  docs/getting-started/downloading-export-batches-keys.md
  docs/getting-started/estimating-costs.md
  docs/index.md
  docs/server_deployment_options.md
  docs/server_functional_requirements.md
  internal/admin/index/index.go
  terraform/README.md
  tools/admin-console/templates/top.html
Labels: approved, cla: yes, lgtm, size/L

#660 feat(secrets-manager): add ability to json-decode secret values and select the value of a map by specifying the key in the secret-name
  internal/setup/setup.go
  pkg/secrets/config.go
  pkg/secrets/json_expander.go
  pkg/secrets/json_expander_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#659 Updating protobuf for v1.5
  go.mod
  go.sum
  internal/pb/export/export.pb.go
  internal/pb/export/export.proto
Labels: approved, cla: yes, lgtm, size/L

#664 Add cleanup test for testing cleanup keys export
  internal/integration/publish_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#666 Create initial Mako project for performance and load tests.
  internal/performance/project.config
Labels: approved, cla: yes, lgtm, size/S

#667 Allow overlapped keys in Debug configurations
  internal/publish/model/exposure_model.go
Labels: approved, cla: yes, lgtm, size/XS

#668 honor max keys per upload configuration
  internal/pb/export/export.pb.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  pkg/api/v1alpha1/exposure_types.go
Labels: approved, cla: yes, lgtm, size/S

#669 Update .gitignore to ignore vscode
  .gitignore
Labels: approved, cla: yes, lgtm, size/XS

#497 Add tests for Google Cloud Storage storage
  internal/storage/google_cloud_storage_test.go
Labels: approved, cla: yes, lgtm, size/L

#674 cache export files
  internal/export/worker.go
Labels: approved, lgtm, size/XS

#675 Refactor integration test package to allow it consumed by others, like performance test
  internal/integration/integration.go
  internal/integration/publish_test.go
Labels: approved, lgtm, size/L
