Repository google/exposure-notifications-server, pull requests merged in 2020-11, with the labels that each got.

#1133 Use non-root in containers
  builders/passwd
  builders/service.dockerfile
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/S

#1137 add http request logging in exposure service
  cmd/exposure/main.go
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#1138 adjust owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1136 better handling of export-import URL config
  internal/exportimport/scheduler.go
  internal/exportimport/scheduler_test.go
Labels: approved, cla: yes, lgtm, size/L

#1142 don't attempt to write key revision data on generated keys
  internal/export/worker.go
  internal/export/worker_test.go
Labels: approved, cla: yes, lgtm, size/M

#1143 change default max records on export file to 500,000
  internal/export/config.go
Labels: approved, cla: yes, lgtm, size/XS

#1128 change default to fail on audience mismatch
  internal/publish/config.go
Labels: approved, cla: yes, lgtm, size/XS

#1145 remove use of EFGS DB columns
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/model/export_model.go
  migrations/000047_AddEFGSUploadConfig.down.sql
Labels: approved, cla: yes, lgtm, size/M

#1153 handle nested paths correctly
  internal/exportimport/scheduler.go
  internal/exportimport/scheduler_test.go
Labels: approved, cla: yes, lgtm, size/L

#1131 adjust symptom onset handling
  internal/generate/config.go
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/publish/config.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  pkg/timeutils/math.go
  pkg/timeutils/math_test.go
  pkg/timeutils/midnight_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1160 make days since onset deterministic in integration test
  internal/integration/integration_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1154 Update local/null provider
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/XS

#1158 Register ocsql views in observability package.
  go.mod
  go.sum
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/M

#1159 Make api requests return chaffed json data.
  go.mod
  go.sum
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/S

#1161 allow a revised key to come in again, as long is it no changey
  internal/publish/database/exposure_test.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish_test.go
Labels: approved, cla: yes, lgtm, size/M

#1163 Incremental e2e tests: use latest service for running tests
  scripts/ci-e2e-test.sh
Labels: approved, cla: yes, lgtm, size/XS

#1139 Add basic latency alerts as Terraform config
  terraform/alerting/alerts.tf
  terraform/alerting/main.tf
  terraform/alerting/notifications.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1166 Add a knob to exclude certain metrics from being exported to
  internal/setup/setup.go
  pkg/observability/config.go
  pkg/observability/noop.go
  pkg/observability/observability.go
  pkg/observability/opencensus.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/S

#1165 Strictify MQL query.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/S

#1167 allow export filename rewriting in mirror job
  cmd/mirror/main.go
  internal/mirror/database/mirror.go
  internal/mirror/database/mirror_test.go
  internal/mirror/mirror.go
  internal/mirror/model/mirror.go
  internal/mirror/model/mirror_test.go
  migrations/000048_AddMirrorRewrite.down.sql
  migrations/000048_AddMirrorRewrite.up.sql
Labels: approved, cla: yes, lgtm, size/L

#1147 complete removal of efgs config
  migrations/000049_remove_efgs_config.down.sql
  migrations/000049_remove_efgs_config.up.sql
Labels: approved, cla: yes, lgtm, size/M

#1169 Delete serverless vpc connector ahead of time
  scripts/ci-terraform.sh
Labels: approved, cla: yes, lgtm, size/XS

#1150 Retry failed imports.
  internal/exportimport/config.go
  internal/exportimport/database/exportimport.go
  internal/exportimport/database/exportimport_test.go
  internal/exportimport/importer.go
  internal/exportimport/importer_test.go
  internal/exportimport/model/file.go
  internal/exportimport/model/file_test.go
  internal/exportimport/scheduler.go
  internal/exportimport/scheduler_test.go
  migrations/000050_AddRetries.down.sql
  migrations/000050_AddRetries.up.sql
Labels: approved, cla: yes, lgtm, size/L

#1170 Parameterize database version
  terraform/database.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/XS

#1172 Switch to Postgres 13, add optional regional replicas
  terraform-e2e-ci/main.tf
  terraform/database.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/M

#1176 Fix for batching when there are more TEKs than the max records settin…
  internal/export/worker.go
  internal/export/worker_test.go
Labels: approved, cla: yes, lgtm, size/M

#1177 Update database utils to match learnings for verification server
  internal/database/database_util.go
Labels: approved, cla: yes, lgtm, size/M

#1179 add maintenance mode for exposure server
  internal/maintenance/maintenance.go
  internal/publish/config.go
  internal/publish/publish_test.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
Labels: approved, cla: yes, lgtm, size/L

#1180 Terrafrom smoke test: stricter db name matching so it won't mess up
  scripts/ci-terraform.sh
Labels: approved, cla: yes, lgtm, size/XS

#1181 change filename pattern, always use batch size of 1
  1605818700-1605819000-0001-ff23e2.zip
  internal/export/exportfile.go
  internal/export/exportfile_test.go
  internal/export/worker.go
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, size/L

#1182 export file adjustments
  1605818700-1605819000-0001-ff23e2.zip
  internal/export/exportfile.go
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/M

#1183 make signature block match
  internal/export/exportfile.go
Labels: approved, cla: yes, lgtm, size/XS

#1175 Remove feature flags for audience checking
  internal/publish/config.go
  internal/publish/publish.go
  internal/verification/phaverify.go
  internal/verification/phaverify_test.go
Labels: approved, cla: yes, lgtm, size/S

#1186 Add REGION to .env
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1187 Attempt to unflake test
  internal/database/database_util.go
Labels: approved, cla: yes, lgtm, size/XS

#1188 Remove dash, sort by ASCII to int
  internal/export/worker.go
  internal/export/worker_test.go
Labels: approved, cla: yes, lgtm, size/M

#1190 restore the original timeline
  docs/regen_exports.md
  internal/export/config.go
  internal/export/exportfile.go
  internal/export/exportfile_test.go
  internal/export/worker.go
  internal/export/worker_test.go
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, size/L

#1191 Adjust the alerting threshold to 10min.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1193 Allow analyzing multiple files with export-analyzer
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/L

#1171 Add a mark/sweep to ExportFile deletion.
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/model/export_model.go
  internal/export/worker.go
  internal/integration/integration_test.go
  migrations/000051_AddPendingDelete.down.sql
  migrations/000051_AddPendingDelete.up.sql
Labels: approved, cla: yes, lgtm, size/L

#1195 parametrize DB name and User name to avoid replacement
  terraform/database.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1196 Match workflows from verification repo
  .github/workflows/codeql-analysis.yml
  .github/workflows/codereview.yaml
  .github/workflows/lock.yml
  .github/workflows/stale.yml
Labels: approved, cla: yes, lgtm, size/M

#1198 Performance test script also pulls images from GCP artifact registry
  scripts/performance.sh
Labels: approved, cla: yes, lgtm, size/S

#1200 Add some missing dependencies to Terraform setup
  terraform/lb.tf
  terraform/storage.tf
Labels: approved, cla: yes, lgtm, size/S
