Repository google/exposure-notifications-server, pull requests merged in 2020-07, with the labels that each got.

#676 Update README.md
  terraform/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#678 rename head branch links to main
  docs/_data/navigation.yml
  docs/_layouts/default.html
  docs/design/verification_protocol.md
  docs/getting-started/deploying.md
  docs/getting-started/estimating-costs.md
  docs/index.md
  docs/server_functional_requirements.md
  examples/export/README.md
  tools/example-verification-signing/main.go
Labels: approved, cla: yes, lgtm, size/M

#681 Fixes to export index.txt file creation
  internal/debugger/handler_debug.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/M

#682 Add github action to deploy from main branch docs folder to gh-pages
  .github/workflows/publish-gh-pages.yml
Labels: approved, cla: yes, lgtm, size/S

#686 Fix typo in internal server implementation
  internal/server/server.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#689 force a pages change
  change.txt
Labels: approved, cla: yes, lgtm, size/XS

#691 gh-pages
  .github/workflows/publish-gh-pages.yml
Labels: approved, cla: yes, lgtm, size/XS

#683 Fix Cache-Control header
  internal/storage/google_cloud_storage.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#687 Use external retry package
  go.mod
  go.sum
  internal/database/database_util.go
Labels: approved, cla: yes, lgtm, size/S

#694 align windows
  internal/integration/integration.go
Labels: approved, cla: yes, lgtm, size/XS

#695 Fix broken links
  docs/getting-started/downloading-export-batches-keys.md
  docs/getting-started/publishing-temporary-exposure-keys.md
Labels: approved, cla: yes, lgtm, size/XS

#697 Set PROJECT_ID on services
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#688 Update handler.go
  internal/generate/handler.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#698 Update observability permissions
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/storage.tf
  terraform/vars.tf
Labels: approved, lgtm, size/L

#700 Verification claims adjustments
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish_test.go
  pkg/api/v1alpha1/verification_types.go
  tools/example-verification-signing/main.go
Labels: approved, cla: yes, lgtm, size/L

#701 Remove test date from verification claims.
  pkg/api/v1alpha1/verification_types.go
  tools/example-verification-signing/main.go
Labels: approved, cla: yes, lgtm, size/XS

#702 use approx time comparison instead of truncating for env differences
  internal/export/database/export_test.go
Labels: approved, cla: yes, lgtm, size/S

#706 Early key release
  docs/getting-started/publishing-temporary-exposure-keys.md
  internal/generate/config.go
  internal/generate/handler.go
  internal/integration/integration.go
  internal/publish/config.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/util/generate.go
Labels: approved, cla: yes, lgtm, size/L

#707 code review comment followup
  internal/publish/config.go
  internal/publish/model/exposure_model.go
Labels: approved, cla: yes, lgtm, size/XS

#708 additional logging on transform failures
  internal/publish/model/exposure_model.go
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/S

#709 add tool for interval numbers and UTC time
  tools/interval/main.go
Labels: approved, cla: yes, lgtm, size/M

#710 Work on v1.5
  internal/generate/config.go
  internal/generate/handler.go
  internal/integration/integration.go
  internal/publish/config.go
  internal/publish/database/exposure.go
  internal/publish/database/exposure_test.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/util/generate.go
  internal/verification/phaverify.go
  internal/verification/phaverify_test.go
  migrations/000031_Addv1dot5Columns.down.sql
  migrations/000031_Addv1dot5Columns.up.sql
  pkg/api/v1alpha1/exposure_types.go
  pkg/api/v1alpha1/verification_types.go
Labels: approved, cla: yes, lgtm, size/XXL

#714 Allow for the min cleanup TTL to be overridden by flag.
  internal/cleanup/cleanup.go
  internal/cleanup/cleanup_test.go
  internal/cleanup/config.go
Labels: approved, cla: yes, lgtm, size/M

#719 docs: Clarify how publish payloads are validated
  docs/getting-started/publishing-temporary-exposure-keys.md
Labels: approved, cla: yes, lgtm, size/S

#718 Implement ExposureKey revisions
  internal/export/database/export_test.go
  internal/federationin/federationin.go
  internal/federationin/federationin_test.go
  internal/generate/handler.go
  internal/integration/publish_test.go
  internal/publish/database/exposure.go
  internal/publish/database/exposure_test.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  migrations/000032_add_revised_transmission_risk.down.sql
  migrations/000032_add_revised_transmission_risk.up.sql
Labels: approved, cla: yes, lgtm, size/XL

#721 docs: fix typo
  docs/server_deployment_options.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#722 V1.5export
  internal/export/exportfile.go
  internal/export/exportfile_test.go
  internal/export/worker.go
  internal/export/worker_test.go
  internal/publish/model/exposure_model.go
  tools/export-generate/main.go
Labels: approved, cla: yes, lgtm, size/L

#724 Have generation service generate report types and key revision.
  internal/generate/config.go
  internal/generate/handler.go
  internal/util/generate.go
Labels: approved, cla: yes, lgtm, size/M

#725 add logging to generate and fix index out of bounds
  internal/generate/handler.go
Labels: approved, cla: yes, lgtm, size/S

#726 fix incorrect if/else clause
  internal/publish/database/exposure.go
Labels: approved, cla: yes, lgtm, size/S

#730 Add Managed Identity auth to Azure Blob Storage
  go.mod
  go.sum
  internal/storage/azure_blobstore.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#731 Don't stale enhancements
  .github/workflows/stale.yml
Labels: approved, cla: yes, lgtm, size/XS

#733 Rewrite integration test to incorporate retries
  internal/integration/client.go
  internal/integration/en_api.go
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/integration/publish_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#736 Integration tests use real GCS
  internal/integration/helpers.go
  internal/integration/integration_test.go
Labels: approved, cla: yes, lgtm, size/M

#737 add a command line tool for calculating the expected HMAC from a publ…
  tools/hmac-calculator/main.go
Labels: approved, cla: yes, lgtm, size/M

#732 up the default key batch size. Supports early key release and post di…
  internal/publish/config.go
Labels: approved, cla: yes, lgtm, size/XS

#739 handle partial batch cleanup error
  internal/export/database/export.go
Labels: approved, cla: yes, lgtm, size/XS

#742 Move server into pkg
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/debugger/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/generate/main.go
  internal/integration/helpers.go
  pkg/server/metrics.go
  pkg/server/server.go
Labels: approved, cla: yes, lgtm, size/S

#743 Remove retry (moved to separate library)
  pkg/retry/retry.go
Labels: approved, cla: yes, lgtm, size/L

#744 Use tagged version of go-gcpkms
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/M

#740 Add encrypt/decrypt operations to key management interface
  go.sum
  pkg/api/v1alpha1/exposure_types.go
  pkg/keys/aws_kms.go
  pkg/keys/azure_keyvault.go
  pkg/keys/google_cloud_kms.go
  pkg/keys/hashicorp_vault.go
  pkg/keys/hashicorp_vault_test.go
  pkg/keys/keys.go
  pkg/keys/noop.go
Labels: approved, cla: yes, lgtm, size/L

#713 Load test for cleanup exports
  Makefile
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/performance/cleanup_test.go
Labels: approved, cla: yes, lgtm, size/L

#752 Fix exposure-client tool
  tools/exposure-client/main.go
Labels: approved, cla: yes, lgtm, size/M

#747 Retry database reads
  internal/admin/authorizedapps/save.go
  internal/admin/authorizedapps/view.go
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database/authorized_app_test.go
  internal/authorizedapp/database_provider.go
  internal/export/database/export.go
  internal/federationin/database/federationin.go
  internal/federationout/database/federationout.go
  internal/publish/database/exposure.go
  internal/publish/database/exposure_test.go
  internal/setup/setup.go
  internal/verification/database/health_authority_db.go
Labels: approved, cla: yes, lgtm, size/XXL

#748 Configure max conns
  terraform/README.md
  terraform/database.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/S

#755 accept keys that are still valid into the minimum window
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
Labels: approved, cla: yes, lgtm, size/M

#758 Rename feature..md to feature.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#759 Actually exempt enhancements from stale
  .github/workflows/stale.yml
Labels: approved, cla: yes, lgtm, size/XS

#761 Internal structure for revision token
  internal/pb/revision.pb.go
  internal/pb/revision.proto
  internal/revision/revision.go
  internal/revision/revision_test.go
Labels: approved, cla: yes, lgtm, size/XL

#762 Fix broken table
  docs/getting-started/publishing-temporary-exposure-keys.md
Labels: approved, cla: yes, lgtm, size/S

#760 Use external signalcontext for interrupts
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/debugger/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/generate/main.go
  go.mod
  go.sum
  internal/interrupt/context.go
  internal/interrupt/interrupt.go
Labels: approved, cla: yes, lgtm, size/M

#763 Trim strings in admin console to avoid config mistakes.
  internal/admin/authorizedapps/form.go
  internal/admin/exports/form.go
  internal/admin/healthauthority/form.go
  internal/admin/siginfo/form.go
  internal/admin/time.go
Labels: approved, cla: yes, lgtm, size/S

#764 Load test for exporting keys at scale
  Makefile
  internal/performance/cleanup_test.go
  internal/performance/export_test.go
  internal/performance/export_test_benchmark.config
Labels: approved, cla: yes, lgtm, size/XL

#765 Managed revision keys
  internal/publish/config.go
  internal/revision/database/revision.go
  internal/revision/database/revision_test.go
  internal/revision/revision.go
  internal/revision/revision_test.go
  migrations/000033_AddRevisionTokenKeys.down.sql
  migrations/000033_AddRevisionTokenKeys.up.sql
  pkg/keys/in_memory.go
Labels: approved, cla: yes, lgtm, size/XL

#769 Setup mako for uploading load test metrics to server
  go.mod
  go.sum
  internal/performance/export_test.go
  internal/performance/export_test_benchmark.config
  internal/performance/helper.go
  scripts/performance.sh
Labels: approved, cla: yes, lgtm, size/L

#770 Add bypass revision token to per-app settings.
  internal/admin/authorizedapps/form.go
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/model/authorized_app_model.go
  migrations/000034_AddRevisionTokenBypass.down.sql
  migrations/000034_AddRevisionTokenBypass.up.sql
  tools/admin-console/templates/authorizedapp.html
Labels: approved, cla: yes, lgtm, size/M

#771 Hook up revision tokens
  internal/export/database/export_test.go
  internal/federationin/federationin.go
  internal/federationin/federationin_test.go
  internal/generate/handler.go
  internal/integration/helpers.go
  internal/publish/config.go
  internal/publish/database/exposure.go
  internal/publish/database/exposure_test.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/revision/database/revision.go
  internal/revision/database/revision_test.go
  internal/revision/revision.go
  internal/revision/revision_test.go
  internal/serverenv/env.go
  internal/setup/setup_test.go
  pkg/api/v1alpha1/exposure_types.go
  pkg/keys/config.go
  pkg/keys/keys.go
  pkg/keys/noop.go
  terraform/key_management.tf
  terraform/secrets.tf
  terraform/service_exposure.tf
Labels: approved, cla: yes, lgtm, size/XL, ¯\_(ツ)_/¯

#775 Support chaff requests for exposures
  docs/getting-started/publishing-temporary-exposure-keys.md
  go.mod
  go.sum
  internal/publish/publish.go
  internal/publish/publish_test.go
Labels: approved, cla: yes, lgtm, size/M

#772 Install gcloud in presubmit test image, use gcloud authenticating with docker
  docker/presubmit-test.dockerfile
  scripts/performance.sh
Labels: approved, cla: yes, lgtm, size/S

#776 Fix UI-model connections
  tools/admin-console/templates/authorizedapp.html
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#777 Fix dockerfile for presubmit-test by adding missing path
  docker/presubmit-test.dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#778 Fix performance test package, prevent future breakages by compiling in presubmit test
  internal/performance/export_test.go
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/XS

#779 add test case for nil transmission risk vector
  internal/publish/model/exposure_model_test.go
Labels: approved, cla: yes, lgtm, size/S

#780 add omitempty to verification claims transmission risk
  pkg/api/v1alpha1/verification_types.go
Labels: approved, cla: yes, lgtm, size/XS

#783 Check that the incoming regions list isn't empty.
  internal/publish/publish.go
  internal/publish/publish_test.go
Labels: approved, cla: yes, lgtm, size/S

#785 update verification protocol accepted claims in design doc
  docs/design/verification_protocol.md
Labels: approved, cla: yes, lgtm, size/S

#781 add whaught to reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#787 Update envconfig
  go.mod
  go.sum
  internal/performance/helper.go
  internal/setup/setup.go
  internal/setup/setup_test.go
  pkg/secrets/resolver.go
Labels: approved, cla: yes, lgtm, size/S

#790 Fix presubmit test bug to surface error message better
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/S

#788 Handle slices of secrets
  internal/integration/helpers.go
  internal/setup/setup_test.go
  pkg/secrets/config.go
  pkg/secrets/in_memory.go
  pkg/secrets/json_expander_test.go
  pkg/secrets/noop.go
  pkg/secrets/resolver.go
  pkg/secrets/resolver_test.go
  pkg/secrets/secrets.go
Labels: approved, cla: yes, lgtm, size/L

#798 Add README for performance test
  internal/performance/README.md
Labels: approved, cla: yes, lgtm, size/XS
