Repository google/exposure-notifications-server, pull requests merged in 2020-08, with the labels that each got.

#801 Move util package from internal to pkg so it can be used to generate …
  internal/generate/handler.go
  internal/integration/integration_test.go
  internal/performance/export_test.go
  internal/publish/publish_test.go
  pkg/util/generate.go
  tools/export-generate/main.go
  tools/exposure-client/main.go
Labels: approved, cla: yes, lgtm, size/S

#802 Support managing envvars with terraform, but deploying with our script
  builders/deploy.yaml
  builders/migrate.yaml
  builders/promote.yaml
  terraform/database.tf
  terraform/main.tf
  terraform/secrets.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#803 Support custom domains
  terraform/service_exposure.tf
  terraform/service_federationout.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/M

#805 Comment / lint nits
  internal/publish/publish.go
  internal/revision/database/revision.go
  internal/revision/revision.go
Labels: approved, cla: yes, lgtm, size/S

#807 fix inverted bypass switch.
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/XS

#809 Ensure main's context's are closed
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/debugger/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/generate/main.go
Labels: approved, cla: yes, lgtm, size/M

#810 remove workflow now that main can host github pages
  .github/workflows/publish-gh-pages.yml
Labels: approved, cla: yes, lgtm, size/S

#808 Boilerplate endpoint for key rotation
  cmd/key-rotation/main.go
  internal/integration/helpers.go
  internal/keyrotation/config.go
  internal/keyrotation/server.go
  internal/keyrotation/server_test.go
  internal/publish/config.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/revision/config.go
Labels: approved, cla: yes, lgtm, size/L

#813 make publish test like way faster
  internal/publish/publish_test.go
Labels: approved, cla: yes, lgtm, size/L

#814 use specific errors for revision token issues
  internal/publish/database/exposure.go
  internal/publish/database/exposure_test.go
Labels: approved, cla: yes, lgtm, size/M

#815 add .env to .gitignore
  .gitignore
Labels: approved, cla: yes, lgtm, size/XS

#816 Fix terraform maps -> tuples
  terraform/main.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
Labels: approved, cla: yes, lgtm, size/M

#818 Add pull request template that captures release notes.
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/S

#817 Logic for key rotation
  go.mod
  internal/cleanup/cleanup_test.go
  internal/keyrotation/config.go
  internal/keyrotation/rotate.go
  internal/keyrotation/rotate_test.go
  internal/keyrotation/server.go
  internal/publish/database/exposure.go
  internal/revision/revision.go
Labels: approved, cla: yes, lgtm, size/L

#819 add release process
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/M

#820 Use a db lock for key rotation
  internal/keyrotation/rotate.go
  internal/keyrotation/server.go
Labels: approved, cla: yes, lgtm, size/S

#821 Make it so revision token issues are 4xx instead of 5xx errors.
  internal/publish/publish.go
  internal/publish/publish_test.go
  pkg/api/v1/exposure_types.go
Labels: approved, cla: yes, lgtm, size/L

#823 enforce previously documented restriction on verification certificate…
  internal/publish/publish_test.go
  internal/verification/phaverify.go
  pkg/api/v1/verification_types.go
  pkg/api/v1/veritifcation_types_test.go
Labels: approved, cla: yes, lgtm, size/M

#825 Allow customizing database backup location
  terraform/database.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/XS

#827 implement alternative HMAC calculation
  internal/verification/phaverify.go
  internal/verification/phaverify_test.go
  pkg/verification/utils.go
  pkg/verification/utils_test.go
Labels: approved, cla: yes, lgtm, size/L

#824 Add new key-rotation service to our build/deploy
  docs/getting-started/deploying.md
  internal/debugger/handler_debug.go
  scripts/build
  scripts/deploy
  scripts/promote
  terraform/service_keyrotation.tf
Labels: approved, cla: yes, lgtm, size/L

#826 Add traveler bit to exports
  internal/admin/exports/form.go
  internal/admin/exports/view.go
  internal/export/batcher.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/export/model/export_model.go
  internal/export/worker.go
  migrations/000036_ExportTravellerSettings.down.sql
  migrations/000036_ExportTravellerSettings.up.sql
  tools/admin-console/templates/export.html
Labels: approved, cla: yes, lgtm, size/L

#830 Deletion based off of createdAt of next key
  internal/keyrotation/rotate.go
  internal/keyrotation/rotate_test.go
Labels: approved, cla: yes, lgtm, size/M

#832 Override KeyManagerConfigProvider
  internal/keyrotation/config.go
Labels: approved, cla: yes, lgtm, size/XS

#834 add kms key ring iam role
  terraform/service_keyrotation.tf
Labels: approved, cla: yes, lgtm, size/S

#833 Update docs for new protocol
  docs/design/verification_protocol.md
  docs/getting-started/publishing-temporary-exposure-keys.md
  docs/images/admin_console_add_authorized_application.png
  docs/images/admin_console_landing.png
Labels: approved, cla: yes, lgtm, size/L

#835 fix replace on exposure-client
  tools/exposure-client/main.go
Labels: approved, cla: yes, lgtm, size/XS

#836 Perms
  terraform/service_keyrotation.tf
Labels: approved, cla: yes, lgtm, size/XS

#837 Give key-rotation service acct perms to the secret
  terraform/service_keyrotation.tf
Labels: approved, cla: yes, lgtm, size/XS

#838 Give aad token a unique name
  terraform/service_keyrotation.tf
Labels: approved, cla: yes, lgtm, size/XS

#829 Enabling the verification flow by creating a dummy health authority and a valid verification certificate
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/publish/publish_test.go
  internal/utils/utils.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#839 Minor docs update
  docs/getting-started/estimating-costs.md
  docs/getting-started/publishing-temporary-exposure-keys.md
Labels: approved, cla: yes, lgtm, size/S

#841 Fixing typo in publish_test
  internal/publish/publish_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#843 Observability
  go.mod
  go.sum
  internal/observability/config.go
  internal/observability/generic.go
  internal/observability/noop.go
  internal/observability/observability.go
  internal/observability/resource.go
  internal/serverenv/env.go
Labels: approved, cla: yes, lgtm, size/L

#845 Move Observability to pkg
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/generate/main.go
  cmd/key-rotation/main.go
  docs/getting-started/deploying.md
  internal/cleanup/config.go
  internal/export/config.go
  internal/federationin/config.go
  internal/federationout/config.go
  internal/generate/config.go
  internal/keyrotation/config.go
  internal/publish/config.go
  internal/serverenv/env.go
  internal/setup/setup.go
  internal/setup/setup_test.go
  pkg/observability/config.go
  pkg/observability/generic.go
  pkg/observability/noop.go
  pkg/observability/observability.go
  pkg/observability/resource.go
Labels: approved, cla: yes, lgtm, size/M

#844 Fix performance test
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/performance/export_test.go
Labels: approved, cla: yes, lgtm, size/M

#846 Cleanup observability bits
  internal/serverenv/env.go
  internal/setup/setup.go
  internal/setup/setup_test.go
  pkg/observability/config.go
  pkg/observability/generic.go
  pkg/observability/noop.go
  pkg/observability/observability.go
  pkg/observability/opencensus.go
  pkg/observability/resource.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/L

#847 Add interfaces for various key handlers
  internal/integration/helpers.go
  internal/keyrotation/rotate_test.go
  internal/keyrotation/server_test.go
  internal/publish/publish_test.go
  internal/revision/database/revision_test.go
  internal/revision/revision_test.go
  pkg/keys/in_memory.go
  pkg/keys/keys.go
Labels: approved, cla: yes, lgtm, size/M

#828 Key Rotation E2E Test
  internal/integration/client.go
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/keyrotation/rotate.go
  internal/publish/model/exposure_model.go
  internal/publish/publish.go
  pkg/api/v1/exposure_types.go
  pkg/api/v1alpha1/exposure_types.go
Labels: approved, cla: yes, lgtm, size/L

#850 Always configure a logger on the context
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/debugger/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/generate/main.go
  cmd/key-rotation/main.go
  internal/authorizedapp/database_provider.go
  internal/cleanup/cleanup.go
  internal/database/connection.go
  internal/database/lock.go
  internal/debugger/handler_debug.go
  internal/export/batcher.go
  internal/export/database/export.go
  internal/export/worker.go
  internal/federationin/federationin.go
  internal/federationout/federationout.go
  internal/generate/handler.go
  internal/keyrotation/rotate.go
  internal/logging/logger.go
  internal/metrics/exporter.go
  internal/publish/database/exposure.go
  internal/publish/model/exposure_model.go
  internal/publish/publish.go
  internal/revision/database/revision.go
  internal/revision/revision.go
  internal/setup/setup.go
  pkg/logging/logger.go
  pkg/logging/logger_test.go
  pkg/observability/stackdriver.go
  pkg/secrets/resolver.go
  pkg/server/metrics.go
  pkg/server/server.go
Labels: approved, cla: yes, lgtm, size/L

#852 Add a length check on export (we already have one on upload)
  internal/export/worker.go
  internal/export/worker_test.go
Labels: approved, cla: yes, lgtm, size/S

#853 update functional requirements for v1.5+
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, size/M

#854 do basic validation in the export analyzer
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/M

#857 Fix typo REGOIN -> REGION
  internal/generate/config.go
Labels: approved, cla: yes, lgtm, size/XS

#859 Update releasing instructions
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/M

#840 Integration test works with existing GCP PostgresSQL
  internal/integration/helpers.go
  scripts/e2e_test.sh
Labels: approved, cla: yes, lgtm, size/M

#860 Abort integration script when no project ID
  scripts/e2e_test.sh
Labels: approved, cla: yes, lgtm, size/XS

#863 allow publish to return a partial success/failure
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  pkg/api/v1/exposure_types.go
Labels: approved, cla: yes, lgtm, size/L

#865 Fix revision token validation
  internal/publish/database/exposure.go
  internal/publish/database/exposure_test.go
  internal/revision/revision.go
  internal/revision/revision_test.go
Labels: approved, cla: yes, lgtm, size/L

#867 Improve wording
  docs/server_functional_requirements.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#869 Document export-analyzer
  examples/export/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#870 Allow the same filename to be used across multiple buckets
  migrations/000037_change_unique_index_export_filename.down.sql
  migrations/000037_change_unique_index_export_filename.up.sql
Labels: approved, cla: yes, lgtm, size/M

#871 Update owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#873 Update terraform owners
  terraform/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#872 Remove nested cmd owners
  cmd/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#874 improve export analyzer
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/M

#879 Install terraform in presubmit docker image
  docker/presubmit-test.dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#878 Switch to using tracecontext standard for traces
  pkg/observability/stackdriver.go
  pkg/server/server.go
Labels: approved, cla: yes, lgtm, size/XS

#868 Adding integration test scenario for exposure not yet verified
  internal/integration/integration_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#883 update typical key version to our convention
  tools/admin-console/templates/siginfo.html
Labels: approved, cla: yes, lgtm, size/XS

#885 Azure KeyVault KeyManager - fix decoding bug
  pkg/keys/azure_keyvault.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#887 fix nil pointer when revision token bypass is on.
  internal/publish/database/exposure.go
Labels: approved, cla: yes, lgtm, size/S

#889 add missing -1
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/XS

#890 add option to provide a file age
  tools/export-analyzer/main.go
Labels: approved, cla: yes, lgtm, size/XS

#891 Upgrade to Go 1.15
  Dockerfile
  docker/migrate.dockerfile
  docker/presubmit-test.dockerfile
  docker/protoc.dockerfile
  go.mod
Labels: approved, cla: yes, lgtm, size/S

#849 Reorganize the structure of jwt generation in perf tests
  internal/integration/helpers.go
  internal/publish/publish_test.go
  internal/utils/utils.go
Labels: approved, cla: yes, lgtm, size/L

#896 Add problem and solution of provisioning both nkey server and verific…
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/S

#897 Add debug logging for verification cert issue and tests for expired r…
  internal/publish/config.go
  internal/publish/publish.go
  internal/publish/publish_test.go
Labels: approved, cla: yes, lgtm, size/M

#908 update release instructions
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/XS

#909 fix kms create key
  pkg/keys/google_cloud_kms.go
Labels: approved, cla: yes, lgtm, size/XS

#910 Add notes on updating the main server dep
  RELEASING.md
Labels: approved, cla: yes, lgtm, size/S

#912 Make Terraform more configurabler
  terraform/database.tf
  terraform/key_management.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/M

#918 stackdriver config improvements
  pkg/observability/config.go
  pkg/observability/resource.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/XS

#919 change debug logging
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/XS

#920 add default DB_POOL_HEALTH_CHECK_PERIOD so that pgpxpool keeps connec…
  internal/database/config.go
Labels: approved, cla: yes, lgtm, size/XS

#921 Support destroying key versions in Cloud KMS
  internal/integration/helpers.go
  pkg/keys/google_cloud_kms.go
  pkg/keys/in_memory.go
  pkg/keys/keys.go
Labels: approved, cla: yes, lgtm, size/L

#923 Add additional db related outputs.
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/S

#927 Set default idle and life timeouts
  internal/database/config.go
Labels: approved, cla: yes, lgtm, size/XS

#931 Add trace logging function
  pkg/logging/logger.go
Labels: approved, cla: yes, lgtm, size/S

#933 Add /health
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/generate/main.go
  internal/debugger/server.go
  internal/export/server.go
  internal/keyrotation/server.go
  pkg/server/healthz.go
Labels: approved, cla: yes, lgtm, size/M

#926 Add signing key manager to Vault
  go.mod
  go.sum
  pkg/keys/hashicorp_vault.go
  pkg/keys/hashicorp_vault_test.go
  pkg/keys/keys.go
Labels: approved, cla: yes, lgtm, size/L

#934 tighten up symptom onset defaults, allow partial success
  internal/publish/config.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
Labels: approved, cla: yes, lgtm, size/M

#894 Fix Stackdriver Managed Resource
  pkg/observability/resource.go
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/M

#935 Add output values to public-accessible services.
  terraform/service_exposure.tf
  terraform/service_federationout.tf
Labels: approved, cla: yes, lgtm, size/XS
