Repository google/exposure-notifications-server, pull requests merged in 2021-01, with the labels that each got.

#1253 Refactor Terraform to allow easy override of Cloud Run service annotations
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_export_importer.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/service_jwks.tf
  terraform/service_keyrotation.tf
  terraform/service_mirror.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#1259 add stats retrieval API
  cmd/cleanup-exposure/main.go
  cmd/exposure/main.go
  internal/cleanup/cleanup.go
  internal/jsonutil/marshal_error.go
  internal/metrics/cleanup/measurements.go
  internal/metrics/cleanup/views.go
  internal/publish/config.go
  internal/publish/database/stats.go
  internal/publish/model/stats.go
  internal/publish/model/stats_test.go
  internal/publish/publish.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
  internal/publish/stats.go
  internal/publish/stats_test.go
  internal/utils/utils.go
  internal/verification/authenticate_stats.go
  internal/verification/authenticate_stats_test.go
  internal/verification/config.go
  internal/verification/phaverify.go
  internal/verification/phaverify_test.go
  pkg/api/v1/stats_types.go
Labels: approved, cla: yes, lgtm, size/XXL

#1260 Fix the Cloud Run annotations
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_export_importer.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/service_jwks.tf
  terraform/service_keyrotation.tf
  terraform/service_mirror.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#1261 Remove dupe ctx logger in mains
  cmd/debugger/main.go
  cmd/export-importer/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/generate/main.go
  cmd/jwks-updater/main.go
  cmd/key-rotation/main.go
  cmd/mirror/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1262 Remove Chao :(
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1263 write publish stats in the background
  internal/publish/database/exposure.go
  internal/publish/database/stats.go
  internal/publish/publish_test.go
Labels: approved, cla: yes, lgtm, size/S

#1265 remove unused file
  internal/efgs/regions.go
Labels: approved, cla: yes, lgtm, size/L

#1264 improve test coverage on authorized app database/model
  internal/authorizedapp/database/authorized_app.go
  internal/authorizedapp/database/authorized_app_test.go
  internal/authorizedapp/model/authorized_app_model.go
  internal/authorizedapp/model/authorized_app_model_test.go
Labels: approved, cla: yes, lgtm, size/L

#1266 Add CloudSchedulerJobFailed alert based on log metrics.
  docs/playbooks/alerts/CloudSchedulerJobFailed.md
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/M

#1269 add coverage as part of presubmit
  Makefile
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/S

#1270 don't update health authority in JWKS update, that record doesn't change
  pkg/jwks/jwks.go
Labels: approved, cla: yes, lgtm, size/XS

#1271 readcommitted is right protection level, since it's a simple for update
  internal/publish/database/stats.go
Labels: approved, cla: yes, lgtm, size/XS

#1272 allow stats API to be disabled on a per HA basis. Improve test coverage
  Makefile
  internal/admin/healthauthority/form.go
  internal/admin/healthauthority/save.go
  internal/admin/healthauthority/view.go
  internal/publish/stats_test.go
  internal/verification/authenticate_stats.go
  internal/verification/authenticate_stats_test.go
  internal/verification/database/health_authority_db.go
  internal/verification/database/health_authority_db_test.go
  internal/verification/model/health_authority.go
  internal/verification/model/health_authority_test.go
  migrations/000055_AddDisableHAStats.down.sql
  migrations/000055_AddDisableHAStats.up.sql
  scripts/create_db_migration.sh
  tools/admin-console/templates/healthauthority.html
Labels: approved, cla: yes, lgtm, size/L

#1274 ensure imported keys are future dated
  internal/exportimport/import.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
Labels: approved, cla: yes, lgtm, size/S

#1276 add tests around import future date, fix order bug
  internal/exportimport/import.go
  internal/exportimport/import_test.go
Labels: approved, cla: yes, lgtm, size/L

#1278 Fix typo: ImportResposne -> ImportResponse
  internal/exportimport/import.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1277 publish model to 100% coverage - add tests / remove dead code
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
Labels: approved, cla: yes, lgtm, size/L

#1275 Make admin-console deployable
  builders/admin-console.dockerfile
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
  builders/server.dockerfile
  cmd/admin-console/main.go
  cmd/admin-console/templates/authorizedapp.html
  cmd/admin-console/templates/bottom.html
  cmd/admin-console/templates/error.html
  cmd/admin-console/templates/export-importer.html
  cmd/admin-console/templates/export.html
  cmd/admin-console/templates/healthauthority.html
  cmd/admin-console/templates/index.html
  cmd/admin-console/templates/mirror.html
  cmd/admin-console/templates/siginfo.html
  cmd/admin-console/templates/top.html
  go.sum
  internal/admin/authorizedapps/form.go
  internal/admin/authorizedapps/save.go
  internal/admin/authorizedapps/view.go
  internal/admin/config.go
  internal/admin/exportimporters/form.go
  internal/admin/exportimporters/save.go
  internal/admin/exportimporters/view.go
  internal/admin/exports/form.go
  internal/admin/exports/save.go
  internal/admin/exports/view.go
  internal/admin/handle_authorized_apps.go
  internal/admin/handle_authorized_apps_test.go
  internal/admin/handle_export_importers.go
  internal/admin/handle_export_importers_test.go
  internal/admin/handle_exports.go
  internal/admin/handle_exports_test.go
  internal/admin/handle_health_authority.go
  internal/admin/handle_healthz.go
  internal/admin/handle_index.go
  internal/admin/handle_mirrors.go
  internal/admin/handle_mirrors_test.go
  internal/admin/handle_signature_infos.go
  internal/admin/handle_signature_infos_test.go
  internal/admin/healthauthority/form.go
  internal/admin/healthauthority/keys.go
  internal/admin/healthauthority/save.go
  internal/admin/healthauthority/view.go
  internal/admin/index/index.go
  internal/admin/mirrors/form.go
  internal/admin/mirrors/save.go
  internal/admin/mirrors/view.go
  internal/admin/mirrors/view_test.go
  internal/admin/server.go
  internal/admin/siginfo/form.go
  internal/admin/siginfo/save.go
  internal/admin/siginfo/view.go
  terraform/service_admin_console.tf
  terraform/vars.tf
  tools/admin-console/main.go
Labels: approved, cla: yes, lgtm, size/XXL

#1280 Clean up nits from admin-console review
  internal/admin/handle_authorized_apps.go
  internal/admin/handle_export_importers.go
  internal/admin/handle_exports.go
  internal/admin/handle_health_authority.go
Labels: approved, cla: yes, lgtm, size/L

#1281 Add ability to alert when humans access secrets
  docs/playbooks/alerts/HumanAccessedSecret.md
  docs/playbooks/alerts/HumanDecryptedValue.md
  terraform/alerting/alerts.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1282 Allow generate service to take up to 2min to complete
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1283 Output signature in admin-console for new export configs
  cmd/admin-console/templates/siginfo.html
  internal/admin/handle_signature_infos.go
Labels: approved, cla: yes, lgtm, size/M

#1284 Fix dockerfile names
  builders/admin-console.dockerfile
  builders/service.dockerfile
Labels: approved, cla: yes, lgtm, size/S

#1285 Set admin-console templates path in Terraform
  terraform/service_admin_console.tf
Labels: approved, cla: yes, lgtm, size/XS

#1286 Document accessing the admin console
  docs/getting-started/deploying.md
Labels: approved, cla: yes, lgtm, size/S

#1287 Allow cleanup-export 10min
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1236 Move metric views closer to where it's actually being used.
  internal/cleanup/cleanup.go
  internal/cleanup/metrics.go
  internal/export/batcher.go
  internal/export/metrics.go
  internal/export/worker.go
  internal/federationin/federationin.go
  internal/federationin/metrics.go
  internal/federationout/federationout.go
  internal/federationout/metrics.go
  internal/keyrotation/metrics.go
  internal/keyrotation/rotate.go
  internal/metrics/cleanup/measurements.go
  internal/metrics/export/measurements.go
  internal/metrics/federationin/measurements.go
  internal/metrics/federationout/measurements.go
  internal/metrics/metricsware/cleanup.go
  internal/metrics/metricsware/export.go
  internal/metrics/metricsware/federationin.go
  internal/metrics/metricsware/federationout.go
  internal/metrics/metricsware/publish.go
  internal/metrics/metricsware/rotate.go
  internal/metrics/publish/measurements.go
  internal/metrics/rotate/measurements.go
  internal/publish/metrics.go
  internal/publish/publish.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
Labels: approved, cla: yes, size/XL

#1289 add test coverage on publish packages, remove dead code
  internal/publish/database/exposure.go
  internal/publish/database/exposure_test.go
  internal/publish/database/stats_test.go
  internal/publish/stats.go
  internal/publish/stats_test.go
Labels: approved, cla: yes, lgtm, size/L

#1290 increase test coverage, refactor duplicate code.
  internal/exportimport/database/exportimport.go
  internal/exportimport/database/exportimport_test.go
  internal/exportimport/model/exportimport.go
  internal/exportimport/model/exportimport_test.go
  internal/exportimport/model/file.go
  internal/exportimport/model/importkeys.go
  internal/flag/flag_test.go
  internal/jsonutil/marshal.go
  internal/jsonutil/marshal_test.go
  internal/jsonutil/unmarshal_test.go
  internal/verification/model/health_authority.go
  pkg/keys/ecdsa_pem.go
  pkg/keys/ecdsa_pem_test.go
  pkg/keys/hashicorp_vault.go
  tools/verify/main.go
Labels: approved, cla: yes, lgtm, size/XL

#1292 Parallel tests
  docs/playbooks/playbook_test.go
  internal/admin/handle_authorized_apps_test.go
  internal/admin/handle_export_importers_test.go
  internal/admin/handle_exports_test.go
  internal/admin/handle_mirrors_test.go
  internal/admin/handle_signature_infos_test.go
  internal/authorizedapp/model/authorized_app_model_test.go
  internal/database/connection_test.go
  internal/database/lock_test.go
  internal/e2e/e2e_test.go
  internal/export/batcher_test.go
  internal/export/database/export_test.go
  internal/export/exportfile_test.go
  internal/export/model/export_model_test.go
  internal/export/server_test.go
  internal/export/worker_test.go
  internal/exportimport/import_test.go
  internal/exportimport/model/exportimport_test.go
  internal/exportimport/model/file_test.go
  internal/exportimport/scheduler_test.go
  internal/federationin/federationin_test.go
  internal/federationout/federationout_test.go
  internal/flag/flag_test.go
  internal/generate/config.go
  internal/integration/helpers.go
  internal/jsonutil/marshal_test.go
  internal/jsonutil/unmarshal_test.go
  internal/keyrotation/rotate_test.go
  internal/metrics/exporter_test.go
  internal/performance/export_test.go
  internal/publish/config.go
  internal/publish/model/exposure_model.go
  internal/publish/model/exposure_model_test.go
  internal/publish/model/stats_test.go
  internal/publish/platform_test.go
  internal/publish/publish_test.go
  internal/publish/stats_test.go
  internal/utils/utils.go
  internal/verification/database/health_authority_db_test.go
  internal/verification/model/health_authority_test.go
  pkg/api/v1/exposure_types.go
  pkg/api/v1/veritifcation_types_test.go
  pkg/api/v1alpha1/verification_types_test.go
  pkg/base64util/decode_test.go
  pkg/cache/cache_test.go
  pkg/jwks/jwks_test.go
  pkg/keys/hashicorp_vault_test.go
  pkg/secrets/cacher_test.go
  pkg/secrets/hashicorp_vault_test.go
  pkg/timeutils/math_test.go
  pkg/timeutils/midnight_test.go
  pkg/verification/utils_test.go
Labels: approved, cla: yes, lgtm, size/L

#1291 increase API packages to 100% coverage
  pkg/api/v1/stats_types.go
  pkg/api/v1/stats_types_test.go
  pkg/api/v1alpha1/verification_types_test.go
Labels: approved, cla: yes, lgtm, size/M

#1293 google_compute_security_policy depends on compute engine API.
  terraform/dos.tf
Labels: approved, cla: yes, lgtm, size/XS

#1288 Create a struct to provide build info
  internal/buildinfo/buildinfo.go
Labels: approved, cla: yes, lgtm, size/S

#1297 don't save newline when importing public keys via JWKS
  internal/admin/handle_authorized_apps.go
  internal/admin/handle_exports.go
  internal/admin/handle_health_authority.go
  internal/admin/handle_signature_infos.go
  internal/admin/time.go
  internal/exportimport/scheduler.go
  internal/federationin/federationin.go
  internal/federationout/federationout.go
  internal/flag/flag.go
  internal/performance/export_test.go
  internal/project/project.go
  internal/project/trim.go
  internal/project/trim_test.go
  internal/verification/model/health_authority.go
  pkg/jwks/jwks.go
  pkg/jwks/jwks_test.go
  pkg/logging/logger.go
Labels: approved, cla: yes, lgtm, size/L

#1298 Manually create metric descriptor at view registration time.
  go.mod
  go.sum
  pkg/observability/stackdriver.go
Labels: approved, cla: yes, lgtm, size/M

#1296 Use gorilla mux.
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/generate/main.go
  go.mod
  go.sum
  internal/debugger/server.go
  internal/export/server.go
  internal/exportimport/server.go
  internal/integration/helpers.go
  internal/keyrotation/server.go
  internal/mirror/mirror_test.go
  internal/mirror/server.go
  pkg/jwks/server.go
  pkg/server/metrics.go
Labels: approved, cla: yes, lgtm, size/L

#1300 fix jwks setting thru
  cmd/jwks-updater/main.go
  internal/jwks/config.go
  internal/jwks/jwks.go
  internal/jwks/jwks_test.go
  internal/jwks/server.go
  internal/verification/database/health_authority_db.go
  internal/verification/database/health_authority_db_test.go
  internal/verification/model/health_authority.go
  internal/verification/model/health_authority_test.go
Labels: approved, cla: yes, lgtm, size/L

#1301 Build all binaries at once (faster build)
  builders/build.yaml
  cmd/jwks/main.go
Labels: approved, cla: yes, lgtm, size/L

#1302 Update docs for jwks rename
  docs/getting-started/deploying.md
Labels: approved, cla: yes, lgtm, size/XS

#1304 correct isolation levels on HA key operations
  internal/verification/database/health_authority_db.go
Labels: approved, cla: yes, lgtm, size/XS

#1305 Add Binary Authorization
  builders/build.yaml
  scripts/build
  terraform/binary_authorization.tf
  terraform/main.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#1294 Remove Latency alert
  docs/playbooks/alerts/LatencyTooHigh.md
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/M

#1307 CSV marshaller for stats
  pkg/api/v1/stats_types.go
  pkg/api/v1/stats_types_test.go
Labels: approved, cla: yes, lgtm, size/L

#1308 chown admin console template files
  builders/admin-console.dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1309 minor coverage bump
  pkg/logging/logger_test.go
Labels: approved, cla: yes, lgtm, size/M

#1310 lint and test coverage for maintenance mode handler
  internal/maintenance/maintenance.go
  internal/maintenance/maintenance_test.go
  internal/publish/config.go
Labels: approved, cla: yes, lgtm, size/M

#1311 Update stackdriver dependency to released version.
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#1312 update cloud scheduler alert
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1314 fix ha public key HTML form input name
  cmd/admin-console/templates/healthauthority.html
  internal/admin/handle_health_authority.go
Labels: approved, cla: yes, lgtm, size/XS

#1315 fix carriage returns in public keys
  internal/admin/handle_health_authority.go
  internal/jwks/jwks.go
Labels: approved, cla: yes, lgtm, size/XS

#1319 Set align rate to 1min
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1320 move all serializable transactions to automatically retry
  go.mod
  internal/authorizedapp/database/authorized_app.go
  internal/database/database.go
  internal/database/lock.go
  internal/e2e/e2e_test.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/exportimport/database/exportimport.go
  internal/federationin/database/federationin.go
  internal/federationout/database/federationout.go
  internal/integration/integration_test.go
  internal/mirror/database/mirror.go
  internal/performance/export_test.go
  internal/revision/database/revision.go
  internal/verification/database/health_authority_db.go
Labels: approved, cla: yes, lgtm, size/L

#1323 Update locking procedure to be strongly consistent
  internal/database/lock.go
  internal/database/lock_test.go
  migrations/000056_UpdateLocks.down.sql
  migrations/000056_UpdateLocks.up.sql
Labels: approved, cla: yes, lgtm, size/L
