Repository google/exposure-notifications-server, pull requests merged in 2021-02, with the labels that each got.

#1324 Switch to ReadCommitted isolation level for locking
  internal/database/lock.go
  internal/database/lock_test.go
Labels: approved, cla: yes, lgtm, size/L

#1325 Drop usage of serializable transactions
  go.mod
  internal/authorizedapp/database/authorized_app.go
  internal/database/database.go
  internal/e2e/e2e_test.go
  internal/export/database/export.go
  internal/export/database/export_test.go
  internal/exportimport/database/exportimport.go
  internal/federationin/database/federationin.go
  internal/federationout/database/federationout.go
  internal/integration/integration_test.go
  internal/mirror/database/mirror.go
  internal/performance/export_test.go
  internal/revision/database/revision.go
  internal/verification/database/health_authority_db.go
Labels: approved, cla: yes, lgtm, size/L

#1330 Only log internal errors on publish, move others to debug level
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/XS

#1327 Move DEBUG SERVER message to warning level
  internal/publish/model/exposure_model.go
Labels: approved, cla: yes, lgtm, size/XS

#1331 Clean up some indexes, run in own transaction
  migrations/000062_ExposureTypes.up.sql
  migrations/000063_FederationInQueryTypes.up.sql
Labels: approved, cla: yes, lgtm, size/S

#1332 add longer timeout for migrate
  cmd/migrate/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1333 More fine-tuning indicies
  builders/migrate.yaml
  migrations/000062_ExposureTypes.up.sql
  migrations/000063_FederationInQueryTypes.up.sql
Labels: approved, cla: yes, lgtm, size/M

#1334 Temporarily remove exposure index creation, inline type changes
  builders/cloud-sql-exec
  builders/migrate.dockerfile
  migrations/000057_AuthorizedAppTypes.down.sql
  migrations/000057_AuthorizedAppTypes.up.sql
  migrations/000058_ExportBatchTypes.down.sql
  migrations/000058_ExportBatchTypes.up.sql
  migrations/000059_ExportConfigTypes.down.sql
  migrations/000059_ExportConfigTypes.up.sql
  migrations/000060_ExportFileTypes.down.sql
  migrations/000060_ExportFileTypes.up.sql
  migrations/000061_ExportImportTypes.down.sql
  migrations/000061_ExportImportTypes.up.sql
  migrations/000062_ExposureTypes.down.sql
  migrations/000062_ExposureTypes.up.sql
  migrations/000063_FederationInQueryTypes.down.sql
  migrations/000063_FederationInQueryTypes.up.sql
  migrations/000064_FederationInSyncTypes.down.sql
  migrations/000064_FederationInSyncTypes.up.sql
  migrations/000065_FederationOutAuthorizationTypes.down.sql
  migrations/000065_FederationOutAuthorizationTypes.up.sql
  migrations/000066_HealthAuthorityTypes.down.sql
  migrations/000066_HealthAuthorityTypes.up.sql
  migrations/000067_HealthAuthorityKeyTypes.down.sql
  migrations/000067_HealthAuthorityKeyTypes.up.sql
  migrations/000068_HealthAuthorityStatsTypes.down.sql
  migrations/000068_HealthAuthorityStatsTypes.up.sql
  migrations/000069_ImportFileTypes.down.sql
  migrations/000069_ImportFileTypes.up.sql
  migrations/000070_ImportFilePublicKeyTypes.down.sql
  migrations/000070_ImportFilePublicKeyTypes.up.sql
  migrations/000071_LockTypes.down.sql
  migrations/000071_LockTypes.up.sql
  migrations/000072_MirrorTypes.down.sql
  migrations/000072_MirrorTypes.up.sql
  migrations/000073_MirrorFileTypes.down.sql
  migrations/000073_MirrorFileTypes.up.sql
  migrations/000074_RevisionKeysTypes.down.sql
  migrations/000074_RevisionKeysTypes.up.sql
  migrations/000075_SignatureInfoTypes.down.sql
  migrations/000075_SignatureInfoTypes.up.sql
Labels: approved, cla: yes, lgtm, size/L

#1337 Do not log lock acquisition failure when the lock is already held
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/S

#1335 Create more precise exposure indices
  migrations/000076_ExposureIdx1.down.sql
  migrations/000076_ExposureIdx1.up.sql
  migrations/000077_ExposureIdx2.down.sql
  migrations/000077_ExposureIdx2.up.sql
  migrations/000078_ExposureIdx3.down.sql
  migrations/000078_ExposureIdx3.up.sql
Labels: approved, cla: yes, lgtm, size/L

#1338 Wait for KMS keys to be ready
  pkg/keys/google_cloud_kms.go
Labels: approved, cla: yes, lgtm, size/S

#1339 Update to latest gcloud in builds
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
Labels: approved, cla: yes, lgtm, size/M

#1340 Recover from panics in main
  cmd/admin-console/main.go
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/debugger/main.go
  cmd/export-importer/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/generate/main.go
  cmd/jwks/main.go
  cmd/key-rotation/main.go
  cmd/migrate/main.go
  cmd/mirror/main.go
Labels: approved, cla: yes, lgtm, size/L

#1341 Pull logger and request_id from context in jwks service
  internal/jwks/handle_update_all.go
  internal/jwks/jwks.go
  internal/jwks/jwks_test.go
  internal/jwks/server.go
  internal/middleware/logger.go
  internal/middleware/middleware.go
  internal/middleware/observability.go
  internal/middleware/request_id.go
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm

#1342 Use custom http client and customizable timeout for jwks
  internal/jwks/config.go
  internal/jwks/jwks.go
  internal/jwks/jwks_test.go
  internal/jwks/server.go
Labels: approved, cla: yes, lgtm, size/S

#1343 Update ignore_changes to avoid recurring diff
  terraform/service_admin_console.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_export_importer.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/service_jwks.tf
  terraform/service_keyrotation.tf
  terraform/service_mirror.tf
Labels: approved, cla: yes, lgtm, size/L

#1344 Refactor generate service to be a proper server, use new middlewares
  cmd/generate/main.go
  cmd/jwks/main.go
  internal/generate/generate_test.go
  internal/generate/handle_generate.go
  internal/generate/server.go
  internal/jwks/jwks_test.go
  internal/project/context.go
  internal/project/context_test.go
  pkg/logging/logger.go
Labels: approved, cla: yes, lgtm, size/L

#1345 Check if connection is valid after acquiring from the pool
  internal/database/connection.go
  internal/database/database.go
Labels: approved, cla: yes, lgtm, size/M

#1346 Use TestContext in tests
  internal/authorizedapp/database/authorized_app_test.go
  internal/cleanup/cleanup_test.go
  internal/database/lock_test.go
  internal/e2e/e2e_test.go
  internal/export/database/export_test.go
  internal/export/server_test.go
  internal/export/worker_test.go
  internal/exportimport/database/exportimport_test.go
  internal/exportimport/import_test.go
  internal/exportimport/importer_test.go
  internal/exportimport/scheduler_test.go
  internal/federationin/database/federationin_test.go
  internal/federationin/federationin_test.go
  internal/federationout/database/federationout_test.go
  internal/federationout/federationout_test.go
  internal/integration/integration_test.go
  internal/keyrotation/rotate_test.go
  internal/keyrotation/server_test.go
  internal/mirror/database/mirror_test.go
  internal/mirror/mirror_test.go
  internal/mirror/server_test.go
  internal/performance/export_test.go
  internal/publish/database/exposure_test.go
  internal/publish/database/performance_test_utils_test.go
  internal/publish/database/stats_test.go
  internal/publish/model/exposure_model_test.go
  internal/publish/publish_test.go
  internal/publish/stats_test.go
  internal/revision/database/revision_test.go
  internal/revision/revision_test.go
  internal/setup/setup_test.go
  internal/storage/filesystem_storage_test.go
  internal/storage/google_cloud_storage_test.go
  internal/verification/authenticate_stats_test.go
  internal/verification/database/health_authority_db_test.go
  internal/verification/phaverify_test.go
  pkg/keys/filesystem_test.go
  pkg/keys/hashicorp_vault_test.go
  pkg/secrets/cacher_test.go
  pkg/secrets/hashicorp_vault_test.go
  pkg/secrets/json_expander_test.go
  pkg/secrets/resolver_test.go
Labels: approved, cla: yes, lgtm, size/L

#1347 Pull context from request in export
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  internal/debugger/server.go
  internal/export/batcher.go
  internal/export/server.go
  internal/export/worker.go
  internal/exportimport/server.go
  internal/generate/server.go
  internal/jwks/server.go
  internal/keyrotation/server.go
  internal/middleware/observability.go
  internal/mirror/server.go
  pkg/server/healthz.go
Labels: approved, cla: yes, lgtm, size/L

#1350 Mount middlewares in other packages
  internal/debugger/handler_debug.go
  internal/debugger/server.go
  internal/e2e/e2e_test.go
  internal/exportimport/importer.go
  internal/exportimport/scheduler.go
  internal/exportimport/server.go
  internal/keyrotation/rotate.go
  internal/keyrotation/server.go
  internal/mirror/mirror.go
  internal/mirror/server.go
Labels: approved, cla: yes, lgtm, size/L

#1351 Move federationin to middleware/server pattern
  cmd/federationin/main.go
  internal/federationin/federationin.go
  internal/federationin/server.go
  internal/integration/helpers.go
Labels: approved, cla: yes, lgtm, size/L

#1352 Rename publishHandler -> publishServer
  cmd/exposure/main.go
  internal/integration/helpers.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
  internal/publish/stats.go
  internal/publish/stats_test.go
Labels: approved, cla: yes, lgtm, size/L

#1353 Move publish to middleware/server pattern
  cmd/exposure/main.go
  go.mod
  go.sum
  internal/integration/client.go
  internal/integration/helpers.go
  internal/publish/database/exposure.go
  internal/publish/model/exposure_model.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
  internal/publish/stats.go
  internal/publish/stats_test.go
Labels: approved, cla: yes, lgtm, size/L

#1355 Move maintenance mode to middleware
  internal/maintenance/maintenance.go
  internal/middleware/maintenance.go
  internal/middleware/maintenance_test.go
  internal/publish/config.go
  internal/publish/publish.go
  internal/publish/publish_test.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
  internal/publish/stats.go
Labels: approved, cla: yes, lgtm, size/L

#1357 Move chaff to middleware
  cmd/exposure/main.go
  internal/integration/helpers.go
  internal/middleware/chaff.go
  internal/publish/publish.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
  internal/publish/stats.go
Labels: approved, cla: yes, lgtm, size/L

#1358 Add sandbox annotation.
  terraform/service_admin_console.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_export_importer.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/service_jwks.tf
  terraform/service_keyrotation.tf
  terraform/service_mirror.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/S

#1359 change default scale to 10
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/XS

#1354 Separate paging and non-paging notification channels
  terraform/alerting/alerts.tf
  terraform/alerting/notifications.tf
  terraform/alerting/variables.tf
  terraform/alerting/workspace.tf
Labels: approved, cla: yes, lgtm, size/M

#1361 Fix bucket name typo
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1362 Check database connection in health check
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/exposure/main.go
  go.mod
  internal/debugger/server.go
  internal/export/server.go
  internal/exportimport/server.go
  internal/federationin/server.go
  internal/generate/server.go
  internal/jwks/server.go
  internal/keyrotation/server.go
  internal/mirror/server.go
  internal/publish/publish.go
  pkg/server/healthz.go
Labels: approved, cla: yes, lgtm, size/M

#1365 Add BETA launch stage annotation.
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/XS

#1367 Drop performance tests
  Makefile
  go.mod
  go.sum
  internal/performance/README.md
  internal/performance/export_test.go
  internal/performance/export_test_benchmark.config
  internal/performance/export_test_benchmark.dev.config
  internal/performance/helper.go
  internal/performance/project.config
  scripts/performance.sh
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/XL

#1368 Move copyright check to GitHub Actions
  .github/workflows/codereview.yaml
  .github/workflows/terraform.yml
  Makefile
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/M

#1364 Add common observability code
  pkg/observability/common.go
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/M

#1369 fix incomplete license
  internal/e2e/e2e_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1363 Move all cloud dependencies to compile-time flags
  Dockerfile
  Makefile
  builders/build.yaml
  docs/getting-started/deploying.md
  go.mod
  go.sum
  internal/cleanup/cleanup_test.go
  internal/e2e/e2e_test.go
  internal/export/server_test.go
  internal/generate/generate_test.go
  internal/integration/client.go
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/mirror/mirror_test.go
  internal/mirror/server_test.go
  internal/setup/setup.go
  internal/setup/setup_test.go
  internal/storage/aws_s3.go
  internal/storage/azure_blobstore.go
  internal/storage/config.go
  internal/storage/filesystem_storage.go
  internal/storage/filesystem_storage_test.go
  internal/storage/google_cloud_storage.go
  internal/storage/google_cloud_storage_test.go
  internal/storage/memory.go
  internal/storage/noop.go
  internal/storage/storage.go
  pkg/keys/aws_kms.go
  pkg/keys/azure_keyvault.go
  pkg/keys/config.go
  pkg/keys/filesystem.go
  pkg/keys/filesystem_test.go
  pkg/keys/google_cloud_kms.go
  pkg/keys/hashicorp_vault.go
  pkg/keys/hashicorp_vault_test.go
  pkg/keys/keys.go
  pkg/keys/testing.go
  pkg/secrets/aws_secrets_manager.go
  pkg/secrets/azure_keyvault.go
  pkg/secrets/cacher.go
  pkg/secrets/config.go
  pkg/secrets/google_secret_manager.go
  pkg/secrets/hashicorp_vault.go
  pkg/secrets/hashicorp_vault_test.go
  pkg/secrets/in_memory.go
  pkg/secrets/json_expander.go
  pkg/secrets/secrets.go
  scripts/build
  scripts/presubmit.sh
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/XXL

#1372 fix windowing logic
  internal/publish/model/exposure_model.go
Labels: approved, cla: yes, lgtm, size/XS

#1371 Move e2e into integration, simplify helpers
  .github/workflows/terraform.yml
  .gitignore
  Makefile
  go.mod
  go.sum
  internal/e2e/e2e_test.go
  internal/enkstest/bootstrap.go
  internal/enkstest/enkstest.go
  internal/enkstest/server.go
  internal/integration/client.go
  internal/integration/helpers.go
  internal/integration/integration_test.go
  internal/project/random.go
  internal/publish/model/exposure_model.go
  internal/utils/utils.go
  scripts/ci-e2e-test.sh
  scripts/ci-terraform.sh
  terraform-e2e-ci/.terraform.lock.hcl
  terraform-e2e-ci/README.md
  terraform-e2e-ci/main.tf
Labels: approved, cla: yes, lgtm, size/XXL

#1374 Set all cron jobs to retry 3 times
  terraform/service_export.tf
  terraform/service_export_importer.tf
  terraform/service_generate.tf
  terraform/service_mirror.tf
Labels: approved, cla: yes, lgtm, size/S

#1376 fix formatting on api docs
  pkg/api/v1/exposure_types.go
Labels: approved, cla: yes, lgtm, size/S

#1377 Set blobstore, key manager, and secret manager in migrate
  builders/migrate.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1378 Set blobstore, key manager, and secret manager on services
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1379 Ignore more annotations in Terraform diff
  terraform/service_admin_console.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_export_importer.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/service_jwks.tf
  terraform/service_keyrotation.tf
  terraform/service_mirror.tf
Labels: approved, cla: yes, lgtm, size/M

#1381 Remove timeout on context (it's set on the http client)
  internal/jwks/jwks.go
Labels: approved, cla: yes, lgtm, size/XS

#1375 add request test, use const for http status
  internal/export/batcher.go
  internal/exportimport/scheduler.go
  internal/keyrotation/rotate.go
  internal/keyrotation/rotate_test.go
  internal/middleware/maintenance_test.go
  internal/mirror/mirror_test.go
  pkg/server/healthz.go
Labels: approved, cla: yes, lgtm, size/M

#1322 improve locking handling for background jobs
  internal/exportimport/scheduler.go
  internal/jwks/handle_update_all.go
  internal/jwks/metrics.go
  internal/keyrotation/metrics.go
  internal/keyrotation/rotate.go
Labels: approved, cla: yes, lgtm, size/M

#1383 Fix metrics.
  internal/publish/publish.go
Labels: approved, cla: yes, lgtm, size/XS

#1384 Update security alerts for HumanAccessSecret and HumanDecryptedValue
  docs/playbooks/alerts/HumanAccessedSecret.md
  docs/playbooks/alerts/HumanDecryptedValue.md
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/S

#1385 Alert immediately
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1389 Use a random prefix instead of hard-coding parent
  pkg/keys/testing.go
Labels: approved, cla: yes, lgtm, size/S

#1387 jwks parallelization limits
  go.mod
  internal/jwks/config.go
  internal/jwks/handle_update_all.go
  internal/jwks/jwks.go
  internal/jwks/jwks_test.go
  internal/jwks/server.go
  internal/verification/model/health_authority.go
  pkg/errcmp/errcmp.go
  terraform/service_jwks.tf
Labels: approved, cla: yes, lgtm, size/L

#1390 simplify error checking in unit tests
  internal/authorizedapp/database/authorized_app_test.go
  internal/exportimport/scheduler_test.go
  internal/mirror/mirror_test.go
  internal/mirror/server_test.go
  internal/publish/database/exposure_test.go
  internal/publish/model/exposure_model_test.go
  internal/verification/authenticate_stats_test.go
  internal/verification/database/health_authority_db_test.go
  internal/verification/model/health_authority_test.go
  internal/verification/phaverify_test.go
  pkg/api/v1/veritifcation_types_test.go
  pkg/cache/cache_test.go
  pkg/keys/ecdsa_pem_test.go
  pkg/keys/filesystem_test.go
Labels: approved, cla: yes, lgtm, size/L

#1391 bump go-chaff to v0.5.0
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#1392 Get Cloud SQL Proxy from new link
  builders/migrate.dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1388 Clean up metrics in the Publish API
  internal/publish/metrics.go
  internal/publish/publish.go
  internal/publish/publish_v1.go
  internal/publish/publish_v1alpha1.go
Labels: approved, cla: yes, lgtm, size/L

#1395 fix API version link
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1396 enforce that STATS_UPLOAD_MINIMUM is set to a value >= 10
  internal/publish/config.go
  internal/publish/publish_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1398 emit metrics for each completed batch
  internal/export/metrics.go
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/S

#1399 Add proper aggregation to the metric.
  internal/publish/metrics.go
Labels: approved, cla: yes, lgtm, size/XS

#1400 add tags on metrics registration
  internal/export/metrics.go
  internal/export/worker.go
Labels: approved, cla: yes, lgtm, size/S

#1401 Set project_id on monitoring service enablement
  terraform/alerting/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1403 Give admin-console signerVerify
  terraform/service_admin_console.tf
Labels: approved, cla: yes, lgtm, size/XS

#1397 Fixing key revision probability for generate and adding a report type confirmed override
  internal/generate/config.go
  internal/generate/handle_generate.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1402 Upgrade to Go 1.16
  .github/workflows/codereview.yaml
  CONTRIBUTING.md
  Makefile
  builders/build.yaml
  cmd/admin-console/main.go
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  cmd/debugger/main.go
  cmd/export-importer/main.go
  cmd/export/main.go
  cmd/exposure/main.go
  cmd/federationin/main.go
  cmd/federationout/main.go
  cmd/generate/main.go
  cmd/jwks/main.go
  cmd/key-rotation/main.go
  cmd/migrate/main.go
  cmd/mirror/main.go
  docker/presubmit-test.dockerfile
  docker/protoc.dockerfile
  go.mod
  internal/debugger/handler_debug.go
  internal/export/exportfile.go
  internal/exportimport/import.go
  internal/exportimport/scheduler.go
  internal/federationin/federationin.go
  internal/integration/client.go
  internal/jsonutil/unmarshal_test.go
  internal/jwks/jwks.go
  internal/publish/publish_test.go
  internal/publish/stats_test.go
  internal/setup/setup_test.go
  internal/storage/aws_s3.go
  internal/storage/filesystem_storage.go
  internal/storage/filesystem_storage_test.go
  internal/storage/google_cloud_storage_test.go
  pkg/keys/filesystem.go
  pkg/keys/filesystem_test.go
  pkg/keys/testing.go
  pkg/secrets/resolver.go
  pkg/secrets/resolver_test.go
  tools/export-analyzer/main.go
  tools/export-generate/main.go
  tools/export-viz/main.go
  tools/exposure-client/main.go
  tools/seed/main.go
  tools/sign/main.go
  tools/unwrap-signature/main.go
  tools/verify/main.go
Labels: approved, cla: yes, lgtm, size/L

#1404 Only cache modules for this project
  builders/build.yaml
Labels: approved, cla: yes, lgtm, size/M

#1405 Add database backup to GCS
  terraform/database.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/L

#1406 Enable query insights
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/XS

#1408 Change into tmpdir when installing linters
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#1407 Migrate admin-console assets to embedded fs
  builders/admin-console.dockerfile
  builders/build.yaml
  internal/admin/config.go
  internal/admin/handle_authorized_apps_test.go
  internal/admin/handle_export_importers_test.go
  internal/admin/handle_exports_test.go
  internal/admin/handle_mirrors_test.go
  internal/admin/handle_signature_infos_test.go
  internal/admin/server.go
  internal/admin/templates/authorizedapp.html
  internal/admin/templates/bottom.html
  internal/admin/templates/error.html
  internal/admin/templates/export-importer.html
  internal/admin/templates/export.html
  internal/admin/templates/healthauthority.html
  internal/admin/templates/index.html
  internal/admin/templates/mirror.html
  internal/admin/templates/siginfo.html
  internal/admin/templates/top.html
  internal/project/util.go
Labels: approved, cla: yes, lgtm, size/L

#1409 add utility methods so we can simplify CSV marshalling
  pkg/api/v1/stats_types.go
Labels: approved, cla: yes, lgtm, size/M
