Repository google/exposure-notifications-server, pull requests merged in 2021-03, with the labels that each got.

#1415 Document debugger service
  docs/getting-started/deploying.md
Labels: approved, cla: yes, lgtm, size/M

#1413 Add uptime check for known hosts
  docs/playbooks/alerts/HostDown.md
  terraform/alerting/alerts.tf
  terraform/alerting/probers.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1417 Update admin console link
  docs/getting-started/publishing-temporary-exposure-keys.md
Labels: approved, cla: yes, lgtm, size/XS

#1418 Use more structured logging for errors
  internal/debugger/handler_debug.go
  internal/export/worker.go
  internal/exportimport/importer.go
  internal/exportimport/scheduler.go
  internal/federationin/federationin.go
  internal/federationout/federationout.go
  internal/mirror/mirror.go
  internal/publish/publish.go
  internal/revision/database/revision.go
  internal/revision/revision.go
  tools/verify/main.go
Labels: approved, cla: yes, lgtm, size/M

#1416 Only log errors on server errors
  internal/publish/publish.go
  internal/revision/revision.go
Labels: approved, cla: yes, lgtm, size/S

#1419 Allow configuring log retention period, default to 14
  terraform/main.tf
  terraform/vars.tf
Labels: approved, cla: yes, lgtm, size/S

#1420 Switch to federation error to warn
  internal/federationin/federationin.go
Labels: approved, cla: yes, lgtm, size/XS

#1421 Remove debugger_hosts and set default to [] to preserve backwards compatibility
  terraform/alerting/probers.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#1423 Remove host alerts for export and federationout
  terraform/alerting/probers.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#1425 Clarify support contract on packages
  CONTRIBUTING.md
  internal/federationin/README.md
  internal/federationout/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1427 Disable v1alpha1 API by default
  docs/_data/navigation.yml
  docs/getting-started/publishing-temporary-exposure-keys.md
  docs/index.md
  docs/server_functional_requirements.md
  internal/publish/config.go
Labels: approved, cla: yes, kind/breaking, lgtm, size/S

#1430 add guide for application configuration
  docs/getting-started/configure_application.md
  docs/images/application01.png
  docs/images/application02.png
  docs/images/application03.png
  docs/images/application04.png
  docs/images/application05.png
  docs/images/application06.png
  docs/images/application07.png
  docs/images/application08.png
  docs/images/application09.png
  docs/images/application10.png
  docs/images/application11.png
  docs/index.md
Labels: approved, cla: yes, kind/docs, lgtm, size/L

#1431 add to nav and fix titles
  docs/_data/navigation.yml
  docs/getting-started/configure_application.md
Labels: approved, cla: yes, lgtm, size/S

#1432 Add stackdriver export failure alert
  docs/playbooks/alerts/StackdriverExportFailed.md
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/M

#1439 change to codeowners
  CODEOWNERS
  OWNERS
Labels: cla: yes

#1441 Switch CODEOWNERS to team
  CODEOWNERS
Labels: cla: yes

#1442 Update cloud scheduler MQL
  terraform/alerting/alerts.tf
Labels: cla: yes

#1443 add ability for export-importer to import an export file w/ travler=true
  internal/exportimport/database/exportimport.go
  internal/exportimport/database/exportimport_test.go
  internal/exportimport/import.go
  internal/exportimport/import_test.go
  internal/exportimport/model/exportimport.go
  internal/exportimport/model/exportimport_test.go
  migrations/000079_ExportImportTraveler.down.sql
  migrations/000079_ExportImportTraveler.up.sql
Labels: cla: yes, kind/enhancement

#1444 improve import file admin console
  internal/admin/handle_export_import_keys.go
  internal/admin/handle_export_importers.go
  internal/admin/server.go
  internal/admin/templates/export-importer.html
  internal/exportimport/database/exportimport.go
  internal/exportimport/model/importkeys.go
Labels: cla: yes

#1445 Print per-package test coverage too
  .github/workflows/ci.yaml
  Makefile
Labels: cla: yes

#1446 Set binauth annotation
  terraform/vars.tf
Labels: cla: yes

#1448 remove duplicated query statements
  terraform/alerting/alerts.tf
Labels: cla: yes

#1449 Only run Terraform checks once
  .github/workflows/terraform.yml
Labels: cla: yes

#1447 Add logs-based metric for when exports are downloaded
  terraform/alerting/alerts.tf
  terraform/alerting/variables.tf
Labels: cla: yes

#1450 add example of admin console tests
  internal/admin/admin_test.go
  internal/admin/handle_signature_infos.go
  internal/admin/handle_signature_infos_test.go
Labels: cla: yes, kind/test-coverage

#1451 add additional background job metrics
  internal/cleanup/cleanup.go
  internal/cleanup/metrics.go
  internal/exportimport/importer.go
  internal/exportimport/metrics.go
  internal/exportimport/scheduler.go
  internal/mirror/metrics.go
  internal/mirror/mirror.go
Labels: cla: yes, kind/enhancement

#1452 first admin console post test
  internal/admin/admin_test.go
  internal/admin/handle_signature_infos_test.go
Labels: cla: yes, kind/test-coverage

#1453 complete siginfo tests
  internal/admin/admin_test.go
  internal/admin/handle_signature_infos_test.go
Labels: cla: yes, kind/test-coverage

#1454 move enkstest to pkg
  internal/integration/integration_test.go
  pkg/enkstest/bootstrap.go
  pkg/enkstest/enkstest.go
  pkg/enkstest/server.go
Labels: cla: yes

#1455 update all deps
  go.mod
  go.sum
Labels: cla: yes

#1457 Move cache lookup into a helper
  pkg/cache/cache.go
Labels: cla: yes

#1458 Add tests for cryptorand package
  pkg/cryptorand/cryptorand_test.go
Labels: cla: yes

#1459 Add more tests for database package
  internal/export/database/export.go
  internal/exportimport/database/exportimport.go
  internal/verification/database/health_authority_db.go
  pkg/database/config.go
  pkg/database/config_test.go
  pkg/database/connection_test.go
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/lock_test.go
Labels: cla: yes

#1460 Try fixing coverage output
  .github/workflows/ci.yaml
Labels: cla: yes

#1461 Clean up duplicate and unused code in util
  internal/export/worker_test.go
  pkg/util/generate.go
  tools/exposure-client/main.go
Labels: cla: yes

#1463 add vaccine status migrations
  migrations/000080_VaccineStatus.down.sql
  migrations/000080_VaccineStatus.up.sql
Labels: cla: yes

#1464 add vaccine status migrations (#1463)
  migrations/000080_VaccineStatus.down.sql
  migrations/000080_VaccineStatus.up.sql
Labels: cla: yes

#1466 Add tests for admin authorized_apps
  internal/admin/admin_test.go
  internal/admin/config.go
  internal/admin/config_test.go
  internal/admin/handle_authorized_apps.go
  internal/admin/handle_authorized_apps_test.go
  internal/admin/handle_export_importers_test.go
  internal/admin/handle_exports_test.go
  internal/admin/handle_mirrors_test.go
  internal/admin/handle_signature_infos_test.go
Labels: cla: yes

#1468 Add admin tests for export import keys
  internal/admin/admin_test.go
  internal/admin/controller.go
  internal/admin/handle_authorized_apps_test.go
  internal/admin/handle_export_import_keys.go
  internal/admin/handle_export_import_keys_test.go
  internal/admin/handle_signature_infos_test.go
Labels: cla: yes

#1469 Add tests for admin export importer
  internal/admin/handle_export_importers.go
  internal/admin/handle_export_importers_test.go
Labels: cla: yes

#1470 Add tests for admin console exports
  internal/admin/admin_test.go
  internal/admin/handle_exports.go
  internal/admin/handle_exports_test.go
Labels: cla: yes

#1471 Add tests for admin health authorities and keys
  internal/admin/admin_test.go
  internal/admin/handle_health_authority.go
  internal/admin/handle_health_authority_test.go
Labels: cla: yes

#1472 Add tests for admin index page
  internal/admin/handle_authorized_apps_test.go
  internal/admin/handle_export_import_keys_test.go
  internal/admin/handle_export_importers_test.go
  internal/admin/handle_exports_test.go
  internal/admin/handle_health_authority_test.go
  internal/admin/handle_healthz_test.go
  internal/admin/handle_index_test.go
  internal/admin/handle_signature_infos_test.go
Labels: cla: yes

#1474 Add more tests for admin routes and template
  internal/admin/admin_test.go
  internal/admin/server_test.go
  internal/admin/template.go
  internal/admin/template_test.go
  internal/admin/util.go
Labels: cla: yes

#1473 Add tests for admin mirrors
  internal/admin/handle_mirrors.go
  internal/admin/handle_mirrors_test.go
Labels: cla: yes

#1434 add support for self report reportType
  internal/export/exportfile.go
  internal/export/exportfile_test.go
  internal/publish/model/exposure_model.go
  internal/publish/publish_test.go
  pkg/api/v1/verification_types.go
Labels: approved, cla: yes, kind/enhancement, size/M

#1476 Update main.go
  tools/example-verification-signing/main.go
Labels: cla: yes

#1479 Add recovery middleware for catching panics
  internal/debugger/server.go
  internal/export/server.go
  internal/exportimport/server.go
  internal/federationin/server.go
  internal/generate/server.go
  internal/jwks/server.go
  internal/keyrotation/server.go
  internal/middleware/recovery.go
  internal/middleware/recovery_test.go
  internal/mirror/server.go
  internal/publish/publish.go
Labels: cla: yes

#1478 Refactor cleanup jobs for forward-progress alerting
  docs/playbooks/alerts/ForwardProgressFailed.md
  docs/playbooks/playbook_test.go
  internal/cleanup/cleanup.go
  internal/cleanup/cleanup_test.go
  internal/cleanup/metrics.go
  terraform/alerting/alerts.tf
  terraform/alerting/variables.tf
  terraform/vars.tf
Labels: cla: yes

#1480 Refactor cleanup to use server patterns and middleware
  cmd/cleanup-export/main.go
  cmd/cleanup-exposure/main.go
  internal/cleanup/cleanup.go
  internal/cleanup/cleanup_export.go
  internal/cleanup/cleanup_export_test.go
  internal/cleanup/cleanup_exposure.go
  internal/cleanup/cleanup_exposure_test.go
  internal/cleanup/cleanup_test.go
  pkg/enkstest/server.go
Labels: cla: yes

#1482 Add forward-progress alerts for mirror service
  internal/generate/handle_generate.go
  internal/mirror/metrics.go
  internal/mirror/mirror.go
  internal/mirror/server.go
  pkg/render/json.go
  terraform/alerting/alerts.tf
Labels: cla: yes

#1483 Use an intermediate proxy for backups
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
  cmd/backup/main.go
  internal/backup/backup.go
  internal/backup/backup_test.go
  internal/backup/config.go
  internal/backup/handle_backup.go
  internal/backup/handle_backup_test.go
  internal/backup/metrics.go
  internal/backup/server.go
  terraform/alerting/alerts.tf
  terraform/database.tf
  terraform/service_admin_console.tf
  terraform/service_backup.tf
Labels: cla: yes

#1485 Align delta
  terraform/alerting/alerts.tf
Labels: cla: yes

#1484 Remove errorw and upgrade to latest ci lint
  .github/workflows/ci.yaml
  .golangci.yaml
  Makefile
Labels: cla: yes

#1486 Add o11y exporter to jwks
  internal/jwks/config.go
Labels: cla: yes

#1487 Switch to fp alerting for jwks and key-rotation services
  internal/jwks/handle_update_all.go
  internal/jwks/metrics.go
  internal/jwks/server.go
  internal/keyrotation/metrics.go
  internal/keyrotation/rotate.go
  internal/keyrotation/server.go
  terraform/alerting/alerts.tf
  terraform/service_keyrotation.tf
Labels: cla: yes

#1488 add metrics for missing public key and more logging
  internal/publish/metrics.go
  internal/publish/publish.go
  internal/verification/phaverify.go
Labels: cla: yes, kind/enhancement

#1491 Update documentation for forward progress
  docs/playbooks/alerts/CloudSchedulerJobFailed.md
  docs/playbooks/alerts/ForwardProgressFailed.md
Labels: cla: yes

#1490 Switch export-importer to forward-progress alerting
  internal/exportimport/handle_import.go
  internal/exportimport/handle_importer_test.go
  internal/exportimport/handle_schedule.go
  internal/exportimport/handle_schedule_test.go
  internal/exportimport/metrics.go
  internal/exportimport/server.go
  terraform/alerting/alerts.tf
  terraform/service_export_importer.tf
Labels: cla: yes

#1493 Align points every 1m
  terraform/alerting/alerts.tf
Labels: cla: yes

#1492 Switch export to forward progress
  docs/playbooks/alerts/ForwardProgressFailed.md
  internal/export/batcher.go
  internal/export/metrics.go
  internal/export/server.go
  internal/export/worker.go
  internal/exportimport/handle_import.go
  terraform/alerting/alerts.tf
Labels: cla: yes

#1494 Use alerting configuration instead of MQL
  docs/playbooks/alerts/CloudSchedulerJobFailed.md
  terraform/alerting/alerts.tf
  terraform/alerting/variables.tf
Labels: cla: yes

#1496 Add special "_all" key to apply to all service environments
  terraform/service_admin_console.tf
  terraform/service_backup.tf
  terraform/service_cleanup_export.tf
  terraform/service_cleanup_exposure.tf
  terraform/service_debugger.tf
  terraform/service_export.tf
  terraform/service_export_importer.tf
  terraform/service_exposure.tf
  terraform/service_federationin.tf
  terraform/service_federationout.tf
  terraform/service_generate.tf
  terraform/service_jwks.tf
  terraform/service_keyrotation.tf
  terraform/service_mirror.tf
  terraform/vars.tf
Labels: cla: yes

#1495 Also always log start and finish in debug mode
  go.mod
  go.sum
  internal/backup/handle_backup.go
  internal/cleanup/cleanup_export.go
  internal/cleanup/cleanup_exposure.go
  internal/export/batcher.go
  internal/export/worker.go
  internal/exportimport/handle_import.go
  internal/exportimport/handle_schedule.go
  internal/generate/handle_generate.go
  internal/jwks/handle_update_all.go
  internal/keyrotation/rotate.go
  internal/mirror/mirror.go
  tools/export-viz/main.go
Labels: cla: yes

#1497 Disable nolintlint
  .golangci.yaml
  tools/export-viz/main.go
Labels: cla: yes

#1498 Bump google plugin version to 3.58
  terraform/vars.tf
Labels: cla: yes

#1499 Lower data-layer TTLs
  internal/backup/config.go
Labels: cla: yes

#1500 Add dashboard for export batches
  terraform/alerting/alerts.tf
  terraform/alerting/dashboards.tf
  terraform/alerting/dashboards/export-batches.json
Labels: cla: yes

#1501 Remove presubmit script
  scripts/presubmit.sh
Labels: cla: yes
